import "server-only";

import { readFileSync } from "node:fs";
import { join } from "node:path";

import OpenAI from "openai";
import sharp from "sharp";

import { getHealthVersionPayload } from "@/lib/health/version-info";
import { isOpenAIConfigured } from "@/lib/openai";
import { normalizeImageForOpenAi } from "@/lib/vision/normalize-for-openai";
import { validateOpenAiImageDataUrl } from "@/lib/vision/validate-openai-image-payload";
import { uploadVisionImageFile, deleteVisionImageFile } from "@/lib/vision/upload-vision-file";
import { resolveVisionModel } from "@/lib/vision/resolve-vision-model";

export type VisionProductionSmokeResult = {
  ok: boolean;
  stage: string;
  environment: string;
  commitSha: string;
  model: string | null;
  transport: "file_id" | "data_url" | null;
  openAiRequestId: string | null;
  openAiHttpStatus: number | null;
  openAiErrorType: string | null;
  openAiErrorCode: string | null;
  openAiErrorMessage: string | null;
  outputTextPreview: string | null;
  image: {
    source: string;
    mimeType: string | null;
    byteLength: number | null;
    width: number | null;
    height: number | null;
    headHex32: string | null;
    openable: boolean;
  };
  structure: {
    inputIsArray: boolean;
    roleIsUser: boolean;
    contentIsArray: boolean;
    hasInputText: boolean;
    hasInputImage: boolean;
    imageUrlIsString: boolean | null;
    detail: string | null;
    matchesResponsesApi: boolean;
  } | null;
  durationMs: number;
  error: string | null;
  version: ReturnType<typeof getHealthVersionPayload>;
};

function loadKnownGoodJpeg(): Buffer {
  // Prefer committed fixture; fall back to generated bytes if missing in deploy.
  try {
    return readFileSync(join(process.cwd(), "testdata/vision/known-good-64.jpg"));
  } catch {
    // Minimal generated JPEG via sharp (same size family as fixture).
    throw new Error("fixture_missing");
  }
}

async function ensureJpegBuffer(): Promise<Buffer> {
  try {
    return loadKnownGoodJpeg();
  } catch {
    return sharp({
      create: {
        width: 64,
        height: 64,
        channels: 3,
        background: { r: 32, g: 96, b: 160 },
      },
    })
      .jpeg({ quality: 90 })
      .toBuffer();
  }
}

/**
 * Production vision smoke: known-good JPEG through normalize → validate →
 * Files API (preferred) / data URL → Responses API.
 * No user auth; rate-limited by the route.
 */
export async function runVisionProductionSmoke(): Promise<VisionProductionSmokeResult> {
  const started = Date.now();
  const version = getHealthVersionPayload();
  const base: VisionProductionSmokeResult = {
    ok: false,
    stage: "init",
    environment: version.environment,
    commitSha: version.commitSha,
    model: null,
    transport: null,
    openAiRequestId: null,
    openAiHttpStatus: null,
    openAiErrorType: null,
    openAiErrorCode: null,
    openAiErrorMessage: null,
    outputTextPreview: null,
    image: {
      source: "testdata/vision/known-good-64.jpg",
      mimeType: null,
      byteLength: null,
      width: null,
      height: null,
      headHex32: null,
      openable: false,
    },
    structure: null,
    durationMs: 0,
    error: null,
    version,
  };

  if (!isOpenAIConfigured()) {
    return {
      ...base,
      stage: "config",
      error: "OPENAI_API_KEY not configured",
      durationMs: Date.now() - started,
    };
  }

  let fileId: string | null = null;
  try {
    const raw = await ensureJpegBuffer();
    base.stage = "normalize";
    const normalized = await normalizeImageForOpenAi({
      buffer: raw,
      profile: "compact",
      diagnosticId: "vdiag_prod_smoke",
    });
    base.stage = "validate";
    const validated = await validateOpenAiImageDataUrl({
      dataUrl: normalized.dataUrl,
      diagnosticId: "vdiag_prod_smoke",
    });
    base.image = {
      source: "testdata/vision/known-good-64.jpg",
      mimeType: validated.mimeType,
      byteLength: validated.byteLength,
      width: validated.width,
      height: validated.height,
      headHex32: validated.headHex32,
      openable: validated.openable,
    };

    const model = resolveVisionModel();
    base.model = model;

    let imagePart:
      | { type: "input_image"; file_id: string; detail: "low" }
      | { type: "input_image"; image_url: string; detail: "low" };

    base.stage = "files_upload";
    try {
      const uploaded = await uploadVisionImageFile({
        buffer: validated.buffer,
        mimeType: validated.mimeType,
        diagnosticId: "vdiag_prod_smoke",
      });
      fileId = uploaded.fileId;
      base.transport = "file_id";
      imagePart = {
        type: "input_image",
        file_id: uploaded.fileId,
        detail: "low",
      };
    } catch {
      base.transport = "data_url";
      imagePart = {
        type: "input_image",
        image_url: validated.dataUrl,
        detail: "low",
      };
    }

    const input = [
      {
        role: "user" as const,
        content: [
          {
            type: "input_text" as const,
            text: "Reply with exactly: OK",
          },
          imagePart,
        ],
      },
    ];

    base.structure = {
      inputIsArray: true,
      roleIsUser: true,
      contentIsArray: true,
      hasInputText: true,
      hasInputImage: true,
      imageUrlIsString:
        "image_url" in imagePart ? typeof imagePart.image_url === "string" : null,
      detail: imagePart.detail,
      matchesResponsesApi:
        imagePart.type === "input_image" &&
        (imagePart.detail === "low" || imagePart.detail === "high") &&
        ("file_id" in imagePart ||
          ("image_url" in imagePart && typeof imagePart.image_url === "string")),
    };

    base.stage = "openai_responses";
    const client = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
      maxRetries: 0,
    });
    const response = await client.responses.create({
      model,
      max_output_tokens: 64,
      input,
    });

    const text = (response.output_text ?? "").trim();
    base.openAiRequestId =
      typeof response.id === "string" ? response.id : null;
    base.openAiHttpStatus = 200;
    base.outputTextPreview = text.slice(0, 120);
    base.ok = /OK/i.test(text) || text.length > 0;
    base.stage = base.ok ? "completed" : "empty_output";
    base.error = base.ok ? null : "empty_or_unexpected_output";
    base.durationMs = Date.now() - started;
    return base;
  } catch (error) {
    const err = error as {
      status?: number;
      requestID?: string;
      error?: { type?: string; code?: string; message?: string };
      message?: string;
    };
    base.openAiHttpStatus = typeof err.status === "number" ? err.status : null;
    base.openAiRequestId = err.requestID ?? null;
    base.openAiErrorType = err.error?.type ?? null;
    base.openAiErrorCode = err.error?.code ?? null;
    base.openAiErrorMessage =
      err.error?.message?.slice(0, 400) ??
      (error instanceof Error ? error.message.slice(0, 400) : String(error));
    base.error = base.openAiErrorMessage;
    base.durationMs = Date.now() - started;
    return base;
  } finally {
    if (fileId) {
      await deleteVisionImageFile(fileId);
    }
  }
}
