import type { ArtifactContextRule } from "@/lib/quality-engine/context/types"

export const salesContextRule: ArtifactContextRule = {
  preferLayers: [
    "business_profile",
    "company",
    "brand",
    "industry",
    "reference",
    "template",
    "past_deliverables",
    "rules",
    "deliverable",
  ],
  preferCategories: [
    "business_profile",
    "company",
    "brand",
    "industry",
    "reference",
    "template",
    "past_deliverables",
    "rules",
    "deliverable",
  ],
  preferTags: [
    "sales",
    "cta",
    "product",
    "service",
    "strength",
    "customer_pain",
    "pitch",
    "sales_material",
  ],
  excludeLayers: [],
  excludeCategories: [],
  excludeTags: ["contract_only", "blog_seo", "excel_formula", "seo"],
  maxPastArtifacts: 3,
  keywordBoosts: [
    "営業",
    "提案",
    "顧客",
    "課題",
    "強み",
    "cta",
    "商品",
    "サービス",
  ],
}
