/**
 * Phase 3-1 — complete external integration inventory from main source facts.
 * Do not mark Production Live from connection UI alone.
 */

import type { ExternalServiceInventoryEntry } from "./types";

export const EXTERNAL_SERVICE_INVENTORY: readonly ExternalServiceInventoryEntry[] =
  [
    {
      serviceName: "Google Drive",
      serviceId: "google_drive",
      classification: "Partial",
      mode: "production",
      implementationFiles: [
        "lib/integrations/google-drive/client.ts",
        "lib/integrations/google-drive/provider.ts",
        "lib/integrations/google/drive/service.ts",
        "lib/integrations/google/drive/api-client.ts",
        "lib/integrations/upload-service.ts",
        "lib/integrations/deliverable-bridge.ts",
      ],
      oauthFiles: [
        "lib/integrations/google/oauth.ts",
        "lib/integrations/google/oauth-service.ts",
        "lib/integrations/google/token-manager.ts",
      ],
      callbackRoutes: [
        "app/api/external-services/google/oauth/authorize/route.ts",
        "app/api/external-services/google/oauth/callback/route.ts",
        "app/api/integrations/oauth/google-drive/authorize/route.ts",
        "app/api/integrations/oauth/google-drive/callback/route.ts",
      ],
      tokenStore: "db_plaintext",
      tokenStoreDetail:
        "atlas_google_oauth_credentials (plaintext access/refresh) + in-memory cache",
      adapter: "google_drive_upload_provider",
      registry: [
        "lib/integrations/providers/upload-registry.ts",
        "lib/integrations/external-services/registry.ts",
        "lib/integrations/registry.ts",
        "lib/connectors/registry.ts",
      ],
      executor: "lib/integrations/upload-service.ts",
      automationStep: null,
      automationPath: "legacy_only",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
        "components/workspace/google-drive-panel.tsx",
        "components/workspace/google-drive-upload-panel.tsx",
      ],
      environmentVariables: [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "GOOGLE_REDIRECT_URI",
        "OAUTH_STATE_SECRET",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status:
        "Live UI/API + legacy deliverable upload; not a V2 Automation external step",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "weak",
      successCriteria: [
        "fileId from Drive API",
        "webViewLink or constructed Drive URL",
        "upload HTTP success with JSON id",
        "checksum not verified",
        "re-fetch not required",
      ],
      notes: [
        "Upload registry only registers google_drive",
        "V2 production-step-registry has no google_drive step",
        "webViewLink falls back to constructed URL when missing",
      ],
    },
    {
      serviceName: "Gmail",
      serviceId: "gmail",
      classification: "Partial",
      mode: "unwired",
      implementationFiles: [
        "lib/integrations/google/gmail/service.ts",
        "lib/integrations/google/gmail/api-client.ts",
        "lib/integrations/google/gmail/client.ts",
      ],
      oauthFiles: [
        "lib/integrations/google/oauth.ts",
        "lib/integrations/google/oauth-service.ts",
        "lib/integrations/google/token-manager.ts",
      ],
      callbackRoutes: [
        "app/api/external-services/google/oauth/authorize/route.ts",
        "app/api/external-services/google/oauth/callback/route.ts",
      ],
      tokenStore: "db_plaintext",
      tokenStoreDetail: "atlas_google_oauth_credentials (shared Google account)",
      adapter: "google_gmail",
      registry: [
        "lib/automation-platform/execution/production-step-registry.ts",
        "lib/integrations/external-services/registry.ts",
        "lib/integrations/registry.ts",
        "lib/connectors/registry.ts",
      ],
      executor: "lib/automation-platform/execution/strict-step-invoker.ts",
      automationStep: "gmail",
      automationPath: "registered_unwired",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
        "components/workspace/google-mail-panel.tsx",
      ],
      environmentVariables: [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "GOOGLE_REDIRECT_URI",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status:
        "UI/API can draft/send; V2 step registered but isLiveAdapterWired=false",
      savesExternalActionId: true,
      savesExternalUrl: false,
      retrySupported: true,
      idempotency: "weak",
      successCriteria: [
        "draftId or sentMessageId",
        "threadId when available",
        "send state from Gmail API",
        "recipient match not revalidated after send",
        "attachment match not checksum-verified",
      ],
      notes: [
        "strictStepInvoker.invokeExternalGate always returns live_adapter_missing when live flag on",
        "Legacy IntegrationService.connect can mark gmail connected without OAuth",
      ],
    },
    {
      serviceName: "Google Calendar",
      serviceId: "google_calendar",
      classification: "Partial",
      mode: "unwired",
      implementationFiles: [
        "lib/integrations/google/calendar/service.ts",
        "lib/integrations/google/calendar/api-client.ts",
      ],
      oauthFiles: [
        "lib/integrations/google/oauth.ts",
        "lib/integrations/google/oauth-service.ts",
      ],
      callbackRoutes: [
        "app/api/external-services/google/oauth/authorize/route.ts",
        "app/api/external-services/google/oauth/callback/route.ts",
      ],
      tokenStore: "db_plaintext",
      tokenStoreDetail: "atlas_google_oauth_credentials (shared Google account)",
      adapter: "google_calendar",
      registry: [
        "lib/automation-platform/execution/production-step-registry.ts",
        "lib/integrations/external-services/registry.ts",
        "lib/connectors/definitions.ts",
      ],
      executor: "lib/automation-platform/execution/strict-step-invoker.ts",
      automationStep: "google_calendar",
      automationPath: "registered_unwired",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
        "components/workspace/google-calendar-panel.tsx",
      ],
      environmentVariables: [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET",
        "GOOGLE_REDIRECT_URI",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status: "UI/API create/update/delete live; V2 adapter unwired",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "none",
      successCriteria: [
        "eventId",
        "htmlLink",
        "timezone from event payload",
        "attendee match not enforced as success gate",
        "Meet requestId uses Date.now() — not stable idempotency",
      ],
      notes: ["V2 requireLiveAdapterAtActivation=true blocks activation"],
    },
    {
      serviceName: "Dropbox",
      serviceId: "dropbox",
      classification: "Partial",
      mode: "unwired",
      implementationFiles: [
        "lib/integrations/dropbox/service.ts",
        "lib/integrations/dropbox/api-client.ts",
        "lib/integrations/dropbox/oauth-service.ts",
      ],
      oauthFiles: [
        "lib/integrations/dropbox/oauth.ts",
        "lib/integrations/dropbox/oauth-service.ts",
        "lib/integrations/dropbox/pkce.ts",
      ],
      callbackRoutes: [
        "app/api/external-services/dropbox/oauth/callback/route.ts",
        "app/api/external-services/[serviceId]/connect/route.ts",
      ],
      tokenStore: "process_memory",
      tokenStoreDetail:
        "__atlasExternalServiceCredentialStore only — NOT in SUPABASE_BACKED_SERVICE_IDS",
      adapter: "dropbox",
      registry: [
        "lib/automation-platform/execution/production-step-registry.ts",
        "lib/integrations/external-services/registry.ts",
      ],
      executor: "lib/automation-platform/execution/strict-step-invoker.ts",
      automationStep: "dropbox",
      automationPath: "registered_unwired",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
        "components/workspace/dropbox-files-panel.tsx",
      ],
      environmentVariables: [
        "DROPBOX_APP_KEY",
        "DROPBOX_APP_SECRET",
        "DROPBOX_REDIRECT_URI",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status:
        "UI/API upload/list/share can hit Dropbox; tokens lost on cold start",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "weak",
      successCriteria: [
        "file id",
        "pathDisplay",
        "revision when returned",
        "shared link optional",
        "checksum not verified",
      ],
      notes: [
        "upload mode=add + autorename=true can duplicate on retry",
        "P0: process-memory token storage",
      ],
    },
    {
      serviceName: "WordPress",
      serviceId: "wordpress",
      classification: "Partial",
      mode: "unwired",
      implementationFiles: [
        "lib/integrations/wordpress/connection-service.ts",
        "lib/integrations/wordpress/api-client.ts",
        "lib/integrations/wordpress/post/service.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [
        "app/api/wordpress/connection/route.ts",
        "app/api/wordpress/connection/verify/route.ts",
      ],
      tokenStore: "db_encrypted",
      tokenStoreDetail:
        "atlas_wordpress_credentials.application_password_ciphertext AES-256-GCM",
      adapter: "wordpress",
      registry: [
        "lib/automation-platform/execution/production-step-registry.ts",
        "lib/integrations/external-services/registry.ts",
        "lib/integrations/registry.ts",
      ],
      executor: "lib/automation-platform/execution/strict-step-invoker.ts",
      automationStep: "wordpress",
      automationPath: "registered_unwired",
      uiConnectionScreens: [
        "components/settings/wordpress-connection-settings.tsx",
      ],
      environmentVariables: [
        "ATLAS_WORDPRESS_CREDENTIALS_ENCRYPTION_KEY",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status: "Application Password connect + create/update post live via API",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "none",
      successCriteria: [
        "postId",
        "status",
        "link/URL",
        "re-fetch not required for success",
      ],
      notes: [
        "POST retry can duplicate posts if response lost",
        "Not OAuth — Application Password auth",
      ],
    },
    {
      serviceName: "X",
      serviceId: "x",
      classification: "Partial",
      mode: "production",
      implementationFiles: [
        "lib/integrations/x/post/service.ts",
        "lib/integrations/x/post/api-client.ts",
        "lib/integrations/x/post/automation.ts",
        "lib/automations/run-automation.ts",
      ],
      oauthFiles: [
        "lib/integrations/x/oauth.ts",
        "lib/integrations/x/oauth-service.ts",
        "lib/integrations/x/pkce.ts",
        "lib/integrations/x/token-manager.ts",
      ],
      callbackRoutes: [
        "app/api/external-services/x/oauth/authorize/route.ts",
        "app/api/external-services/x/oauth/callback/route.ts",
      ],
      tokenStore: "db_plaintext",
      tokenStoreDetail: "atlas_x_oauth_credentials plaintext + memory cache",
      adapter: "x",
      registry: [
        "lib/automation-platform/execution/production-step-registry.ts",
        "lib/integrations/external-services/registry.ts",
      ],
      executor: "lib/integrations/x/post/automation.ts",
      automationStep: "x_post",
      automationPath: "legacy_only",
      uiConnectionScreens: [
        "components/settings/x-connection-settings.tsx",
        "components/workspace/x-post-panel.tsx",
        "components/workspace/x-autopost-panel.tsx",
      ],
      environmentVariables: [
        "X_CLIENT_ID",
        "X_CLIENT_SECRET",
        "X_REDIRECT_URI",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status:
        "Legacy automation + UI can post live (existence confirm); V2 x_post unwired",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "in_process",
      successCriteria: [
        "tweetId",
        "tweetUrl",
        "provider re-read confirmation required",
        "API 200 alone is insufficient",
      ],
      notes: [
        "In-process dedupe TTL only — not durable across instances",
        "Recurring slot idempotency exists separately",
        "Deferred from Phase 3-2 due to posting/OAuth/plan constraints",
      ],
    },
    {
      serviceName: "Slack",
      serviceId: "slack",
      classification: "UI Only",
      mode: "stub",
      implementationFiles: [
        "lib/integrations/registry.ts",
        "lib/connectors/definitions.ts",
        "lib/execution/summaries.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "No token store — OAuth stub enabled:false",
      adapter: null,
      registry: [
        "lib/integrations/registry.ts",
        "lib/connectors/definitions.ts",
      ],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/integrations/integrations-dashboard.tsx",
        "components/connections/connection-provider-card.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Catalog/UI only; no live adapter or OAuth callback",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none — not executable"],
      notes: [
        "Legacy IntegrationService.connect can mark Slack connected without credentials",
        "Sandbox execution summary can say notification sent",
      ],
    },
    {
      serviceName: "Discord",
      serviceId: "discord",
      classification: "UI Only",
      mode: "stub",
      implementationFiles: [
        "lib/integrations/registry.ts",
        "lib/connectors/definitions.ts",
        "lib/execution/summaries.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "No token store",
      adapter: null,
      registry: [
        "lib/integrations/registry.ts",
        "lib/connectors/definitions.ts",
      ],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/integrations/integrations-dashboard.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Catalog/UI only; no live bot/OAuth path",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none — not executable"],
      notes: ["Legacy connect can mark connected without bot validation"],
    },
    {
      serviceName: "Notion",
      serviceId: "notion",
      classification: "Stub",
      mode: "stub",
      implementationFiles: ["lib/integrations/notion/index.ts"],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "stubConnectService marks connected without tokens",
      adapter: null,
      registry: [
        "lib/integrations/external-services/registry.ts",
        "lib/connectors/definitions.ts",
      ],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "stubConnectService placeholder connect",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none — stub connect only"],
      notes: ["P0 risk if stub connect is treated as production readiness"],
    },
    {
      serviceName: "LINE",
      serviceId: "line",
      classification: "Partial",
      mode: "production",
      implementationFiles: [
        "lib/integrations/line/service.ts",
        "lib/integrations/line/messaging.ts",
        "lib/integrations/line/link-store.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [
        "app/api/line/connection/route.ts",
        "app/api/line/webhook/route.ts",
      ],
      tokenStore: "env_secret",
      tokenStoreDetail:
        "LINE_CHANNEL_ACCESS_TOKEN/SECRET in env; user link state in atlas_user_state",
      adapter: null,
      registry: [],
      executor: "lib/integrations/line/messaging.ts",
      automationStep: null,
      automationPath: "notification_only",
      uiConnectionScreens: [
        "components/settings/notification-settings.tsx",
      ],
      environmentVariables: [
        "LINE_CHANNEL_ACCESS_TOKEN",
        "LINE_CHANNEL_SECRET",
        "LINE_BOT_BASIC_ID",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status: "Live push + webhook link; not a V2 external work step",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: true,
      idempotency: "weak",
      successCriteria: [
        "HTTP success from LINE Messaging API",
        "webhookEventId dedupe for inbound",
        "no durable provider message id for outbound evidence",
      ],
      notes: ["Retry after timeout-after-send can duplicate pushes"],
    },
    {
      serviceName: "Microsoft Outlook",
      serviceId: "microsoft_outlook",
      classification: "Unsupported",
      mode: "unsupported",
      implementationFiles: ["lib/connectors/definitions.ts"],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "OAuth stub enabled:false — coming soon",
      adapter: null,
      registry: ["lib/connectors/definitions.ts"],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/connections/connection-provider-card.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Coming soon / unsupported",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none"],
      notes: ["No live Microsoft Graph adapter"],
    },
    {
      serviceName: "Microsoft Teams",
      serviceId: "microsoft_teams",
      classification: "Unsupported",
      mode: "unsupported",
      implementationFiles: ["lib/connectors/definitions.ts"],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "OAuth stub enabled:false — coming soon",
      adapter: null,
      registry: ["lib/connectors/definitions.ts"],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/connections/connection-provider-card.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Coming soon / unsupported",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none"],
      notes: [],
    },
    {
      serviceName: "Webhook",
      serviceId: "webhook",
      classification: "Unsupported",
      mode: "unsupported",
      implementationFiles: [
        "lib/integrations/registry.ts",
        "lib/execution/types.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "No outbound webhook credential store",
      adapter: null,
      registry: ["lib/integrations/registry.ts"],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/integrations/integrations-dashboard.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Catalog trigger_webhook only; liveWebhooks stub disabled",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: [
        "HTTP status (not implemented)",
        "response body policy (not implemented)",
        "signature (not implemented)",
        "retry policy (not implemented)",
      ],
      notes: ["EXECUTION_EXTENSION_STUBS.liveWebhooks.enabled=false"],
    },
    {
      serviceName: "Push Notification",
      serviceId: "push_notification",
      classification: "Partial",
      mode: "production",
      implementationFiles: [
        "lib/push/dispatch.ts",
        "lib/notifications/delivery.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [
        "app/api/push/subscribe/route.ts",
        "app/api/push/vapid-public-key/route.ts",
      ],
      tokenStore: "db_encrypted",
      tokenStoreDetail: "Web Push subscription endpoints stored per user",
      adapter: null,
      registry: [],
      executor: "lib/push/dispatch.ts",
      automationStep: "notify",
      automationPath: "notification_only",
      uiConnectionScreens: [
        "components/settings/notification-settings.tsx",
      ],
      environmentVariables: [
        "NEXT_PUBLIC_VAPID_PUBLIC_KEY",
        "VAPID_PRIVATE_KEY",
        "VAPID_SUBJECT",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status: "Live Web Push delivery; V2 notify step uses notificationIds",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: true,
      idempotency: "in_process",
      successCriteria: [
        "notificationId created",
        "webpush send attempt",
        "no durable provider message id",
      ],
      notes: [
        "ATLAS_WORK_QUEUE_OFFLINE_NOTIFY=1 can create local notify receipts",
      ],
    },
    {
      serviceName: "Email Delivery",
      serviceId: "email_delivery",
      classification: "Partial",
      mode: "unwired",
      implementationFiles: [
        "lib/integrations/google/gmail/service.ts",
        "lib/contact/dispatchers.ts",
      ],
      oauthFiles: ["lib/integrations/google/oauth.ts"],
      callbackRoutes: [],
      tokenStore: "db_plaintext",
      tokenStoreDetail: "Gmail path uses Google OAuth tokens; generic email none",
      adapter: "google_gmail",
      registry: ["lib/connectors/registry.ts"],
      executor: null,
      automationStep: "gmail",
      automationPath: "registered_unwired",
      uiConnectionScreens: [
        "components/workspace/google-mail-panel.tsx",
      ],
      environmentVariables: ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET"],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status: "Only via Gmail; generic email dispatcher is TODO/log-only",
      savesExternalActionId: true,
      savesExternalUrl: false,
      retrySupported: true,
      idempotency: "weak",
      successCriteria: ["Gmail message/draft id when using Gmail path"],
      notes: ["contact/dispatchers explicitly defer email dispatcher"],
    },
    {
      serviceName: "Supabase Storage",
      serviceId: "supabase_storage",
      classification: "Production Live",
      mode: "production",
      implementationFiles: [
        "lib/deliverables/object-storage.ts",
        "lib/attachments/supabase-store.ts",
        "lib/deliverables/storage-backend.ts",
      ],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "env_secret",
      tokenStoreDetail: "SUPABASE_SERVICE_ROLE_KEY / project URL",
      adapter: null,
      registry: [],
      executor: "lib/deliverables/object-storage.ts",
      automationStep: null,
      automationPath: "storage_only",
      uiConnectionScreens: [],
      environmentVariables: [
        "NEXT_PUBLIC_SUPABASE_URL",
        "SUPABASE_SERVICE_ROLE_KEY",
        "NEXT_PUBLIC_SUPABASE_ANON_KEY",
      ],
      productionReachable: true,
      previewReachable: true,
      testOnly: false,
      deprecated: false,
      status:
        "Forced on Vercel production/preview for deliverables/attachments",
      savesExternalActionId: true,
      savesExternalUrl: true,
      retrySupported: true,
      idempotency: "durable",
      successCriteria: [
        "object path stored",
        "hash-path idempotent upload",
        "signed/storage URL available to completion gates",
      ],
      notes: [
        "Non-Vercel NODE_ENV=production may still resolve local backend",
      ],
    },
    {
      serviceName: "S3 / R2",
      serviceId: "s3_r2",
      classification: "Unsupported",
      mode: "unsupported",
      implementationFiles: ["lib/integrations/providers/upload-provider.ts"],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "Not implemented — future provider comment only",
      adapter: null,
      registry: [],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Unsupported / not implemented",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none"],
      notes: ["upload-provider mentions future providers only"],
    },
    {
      serviceName: "YouTube",
      serviceId: "youtube",
      classification: "Stub",
      mode: "stub",
      implementationFiles: ["lib/integrations/youtube/index.ts"],
      oauthFiles: [],
      callbackRoutes: [],
      tokenStore: "none",
      tokenStoreDetail: "stubConnectService",
      adapter: null,
      registry: ["lib/integrations/external-services/registry.ts"],
      executor: null,
      automationStep: null,
      automationPath: "none",
      uiConnectionScreens: [
        "components/settings/external-service-settings.tsx",
      ],
      environmentVariables: [],
      productionReachable: false,
      previewReachable: false,
      testOnly: false,
      deprecated: false,
      status: "Stub connect only",
      savesExternalActionId: false,
      savesExternalUrl: false,
      retrySupported: false,
      idempotency: "n/a",
      successCriteria: ["none"],
      notes: [],
    },
  ] as const;

export function listByClassification(
  classification: ExternalServiceInventoryEntry["classification"],
): ExternalServiceInventoryEntry[] {
  return EXTERNAL_SERVICE_INVENTORY.filter(
    (entry) => entry.classification === classification,
  );
}

export function getInventoryEntry(
  serviceId: ExternalServiceInventoryEntry["serviceId"],
): ExternalServiceInventoryEntry | undefined {
  return EXTERNAL_SERVICE_INVENTORY.find((entry) => entry.serviceId === serviceId);
}
