/**
 * Phase 3-1 — OAuth security audit matrix.
 */

import type { OAuthSecurityAuditEntry } from "./types";

export const OAUTH_SECURITY_AUDIT: readonly OAuthSecurityAuditEntry[] = [
  {
    serviceId: "google_drive",
    hasOAuth: true,
    authorizationUrl: true,
    callback: true,
    stateValidation: true,
    pkce: false,
    nonce: false,
    redirectUriConfigured: true,
    scopesDocumented: true,
    accessToken: true,
    refreshToken: true,
    expiryTracked: true,
    tokenRefresh: true,
    revokedTokenHandling: true,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding: "Tokens stored plaintext in atlas_google_oauth_credentials",
      },
      {
        severity: "P1",
        finding: "No PKCE on Google confidential client authorization URL",
      },
      {
        severity: "P1",
        finding: "openid requested without nonce / id_token validation",
      },
      {
        severity: "P2",
        finding: "No dedicated OAuth audit event stream",
      },
    ],
  },
  {
    serviceId: "gmail",
    hasOAuth: true,
    authorizationUrl: true,
    callback: true,
    stateValidation: true,
    pkce: false,
    nonce: false,
    redirectUriConfigured: true,
    scopesDocumented: true,
    accessToken: true,
    refreshToken: true,
    expiryTracked: true,
    tokenRefresh: true,
    revokedTokenHandling: true,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding: "Shares Google plaintext token store",
      },
      {
        severity: "P1",
        finding: "Scope diagnosis for send vs modify insufficient for V2 gate",
      },
    ],
  },
  {
    serviceId: "google_calendar",
    hasOAuth: true,
    authorizationUrl: true,
    callback: true,
    stateValidation: true,
    pkce: false,
    nonce: false,
    redirectUriConfigured: true,
    scopesDocumented: true,
    accessToken: true,
    refreshToken: true,
    expiryTracked: true,
    tokenRefresh: true,
    revokedTokenHandling: true,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding: "Shares Google plaintext token store",
      },
    ],
  },
  {
    serviceId: "dropbox",
    hasOAuth: true,
    authorizationUrl: true,
    callback: true,
    stateValidation: true,
    pkce: true,
    nonce: "n/a",
    redirectUriConfigured: true,
    scopesDocumented: true,
    accessToken: true,
    refreshToken: true,
    expiryTracked: true,
    tokenRefresh: true,
    revokedTokenHandling: true,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding:
          "Tokens process-memory only; not in SUPABASE_BACKED_SERVICE_IDS; lost on cold start",
      },
      {
        severity: "P1",
        finding:
          "Redirect URI can derive from request origin when DROPBOX_REDIRECT_URI absent",
      },
    ],
  },
  {
    serviceId: "x",
    hasOAuth: true,
    authorizationUrl: true,
    callback: true,
    stateValidation: true,
    pkce: true,
    nonce: "n/a",
    redirectUriConfigured: true,
    scopesDocumented: true,
    accessToken: true,
    refreshToken: true,
    expiryTracked: true,
    tokenRefresh: true,
    revokedTokenHandling: true,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding: "Tokens stored plaintext in atlas_x_oauth_credentials",
      },
      {
        severity: "P1",
        finding: "Disconnect revokes access token only; refresh not revoked",
      },
      {
        severity: "P1",
        finding:
          "Redirect URI can derive from request origin when X_REDIRECT_URI absent",
      },
    ],
  },
  {
    serviceId: "wordpress",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: true,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: true,
    tokenRedaction: true,
    auditLogging: false,
    gaps: [
      {
        severity: "P1",
        finding: "Application Password has no refresh/revoke against WordPress",
      },
      {
        severity: "P2",
        finding: "No organization/tenant isolation",
      },
    ],
  },
  {
    serviceId: "slack",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: false,
    disconnect: false,
    ownerIsolation: false,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: false,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding:
          "Legacy connect can mark Slack connected without OAuth or owner isolation",
      },
    ],
  },
  {
    serviceId: "discord",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: false,
    disconnect: false,
    ownerIsolation: false,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: false,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding:
          "Legacy connect can mark Discord connected without credentials or owner isolation",
      },
    ],
  },
  {
    serviceId: "notion",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: false,
    disconnect: true,
    ownerIsolation: true,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: false,
    auditLogging: false,
    gaps: [
      {
        severity: "P0",
        finding: "stubConnectService returns status connected without OAuth",
      },
    ],
  },
  {
    serviceId: "microsoft_outlook",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: false,
    disconnect: false,
    ownerIsolation: false,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: false,
    auditLogging: false,
    gaps: [
      {
        severity: "P2",
        finding: "Coming soon UI only — unsupported",
      },
    ],
  },
  {
    serviceId: "microsoft_teams",
    hasOAuth: false,
    authorizationUrl: false,
    callback: false,
    stateValidation: false,
    pkce: "n/a",
    nonce: "n/a",
    redirectUriConfigured: false,
    scopesDocumented: false,
    accessToken: false,
    refreshToken: false,
    expiryTracked: false,
    tokenRefresh: false,
    revokedTokenHandling: false,
    reconnect: false,
    disconnect: false,
    ownerIsolation: false,
    tenantIsolation: false,
    tokenEncryption: false,
    tokenRedaction: false,
    auditLogging: false,
    gaps: [
      {
        severity: "P2",
        finding: "Coming soon UI only — unsupported",
      },
    ],
  },
] as const;
