/**
 * Phase 3-1 — Token storage location audit.
 */

import type { TokenStorageAuditEntry } from "./types";

export const TOKEN_STORAGE_AUDIT: readonly TokenStorageAuditEntry[] = [
  {
    serviceId: "google_drive",
    storage: "db_plaintext",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: true,
    expiresAt: true,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail:
      "atlas_google_oauth_credentials plaintext columns; memory cache via credential-store",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "gmail",
    storage: "db_plaintext",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: true,
    expiresAt: true,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail: "Shared Google OAuth credential row (user_id PK)",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "google_calendar",
    storage: "db_plaintext",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: true,
    expiresAt: true,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail: "Shared Google OAuth credential row (user_id PK)",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "dropbox",
    storage: "process_memory",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: true,
    expiresAt: true,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail:
      "__atlasExternalServiceCredentialStore only; schedulePersistExternalAuth not called on Dropbox OAuth complete",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "x",
    storage: "db_plaintext",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: true,
    expiresAt: true,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail: "atlas_x_oauth_credentials plaintext columns + memory cache",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "wordpress",
    storage: "db_encrypted",
    accessTokenEncrypted: true,
    refreshTokenEncrypted: false,
    secretRotation: true,
    ownerId: true,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail:
      "atlas_wordpress_credentials AES-256-GCM application_password_ciphertext",
    severityIfUnsafe: null,
  },
  {
    serviceId: "line",
    storage: "env_secret",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: true,
    ownerId: true,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail:
      "Channel token/secret in env; per-user link ids in atlas_user_state domains",
    severityIfUnsafe: null,
  },
  {
    serviceId: "slack",
    storage: "undefined",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: false,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: false,
    detail: "No token store; legacy global integration memory only",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "discord",
    storage: "undefined",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: false,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: false,
    detail: "No token store; legacy global integration memory only",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "notion",
    storage: "undefined",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: true,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail: "Stub connection status without credentials",
    severityIfUnsafe: "P0",
  },
  {
    serviceId: "webhook",
    storage: "none",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: false,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: false,
    detail: "Unsupported outbound webhook — no secrets",
    severityIfUnsafe: null,
  },
  {
    serviceId: "push_notification",
    storage: "mixed",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: true,
    ownerId: true,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: true,
    detail: "VAPID keys in env; subscriptions persisted per user",
    severityIfUnsafe: null,
  },
  {
    serviceId: "supabase_storage",
    storage: "env_secret",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: true,
    ownerId: true,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: false,
    detail: "Service role key in env; object paths owner-scoped in app logic",
    severityIfUnsafe: null,
  },
  {
    serviceId: "s3_r2",
    storage: "none",
    accessTokenEncrypted: false,
    refreshTokenEncrypted: false,
    secretRotation: false,
    ownerId: false,
    organizationId: false,
    scope: false,
    expiresAt: false,
    lastRefreshAt: false,
    revokedAt: false,
    connectionStatus: false,
    detail: "Unsupported",
    severityIfUnsafe: null,
  },
] as const;

export function listPlaintextOrMemoryTokenStores(): TokenStorageAuditEntry[] {
  return TOKEN_STORAGE_AUDIT.filter(
    (entry) =>
      entry.storage === "db_plaintext" ||
      entry.storage === "process_memory" ||
      entry.severityIfUnsafe === "P0",
  );
}
