import type { FindingRecord } from "./types";

/**
 * Curated P0/P1/P2 findings from main code paths (not speculation).
 * Each evidence path was observed in repository source.
 */
export const DURABLE_SOT_FINDINGS: readonly FindingRecord[] = [
  {
    id: "P0-WQ-FILE-FALLBACK",
    criticality: "P0",
    title: "Work Queue falls back to .data file when Postgres unavailable",
    domain: "Job",
    evidence: [
      "lib/work-queue/store/index.ts:8-22",
      "lib/work-queue/store/file-store.ts:47-50",
      "lib/runtime/ephemeral-fs.ts:8-28",
    ],
    impact: "job_loss",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P0-V2-RUN-MEMORY-SOT",
    criticality: "P0",
    title: "Automation Platform V2 runs/idempotency/occurrence live in process Map",
    domain: "Run",
    evidence: [
      "lib/automation-platform/repository/memory-store.ts:15-28",
      "lib/automation-platform/repository/memory-store.ts:101-125",
      "lib/automation-platform/durable-runs.ts:50-59",
    ],
    impact: "double_execution",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P0-EXTERNAL-BEFORE-EVIDENCE",
    criticality: "P0",
    title: "External action / notify can succeed before durable evidence/persist",
    domain: "ExternalAction",
    evidence: [
      "lib/notifications/service.ts:140-214",
      "lib/deliverables/store.ts:173-174",
      "lib/automation-platform/durable-runs.ts:50-59",
      "lib/work-queue/steps/execute-step.ts:180-232",
    ],
    impact: "external_action_duplicate",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P0-LEGACY-JOB-MEMORY-FALLBACK",
    criticality: "P0",
    title: "Legacy automation jobs fall back to globalThis Map when Supabase missing",
    domain: "Job",
    evidence: ["lib/jobs/job-store.ts:49-56", "lib/jobs/job-store.ts:175-260"],
    impact: "job_loss",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P0-FALSE-COMPLETED-WITHOUT-DURABLE-EVIDENCE",
    criticality: "P0",
    title:
      "Completion/evidence stored via mixed SoT — restart can lose proof while side effects remain",
    domain: "CompletionEvidence",
    evidence: [
      "lib/jobs/completion-evidence.ts:24-80",
      "lib/work-queue/completion-gate.ts",
      "lib/automation-platform/execution/run-completion.ts",
    ],
    impact: "false_completed",
    restartRisk: true,
    multiInstanceRisk: false,
    migrationTarget: true,
  },
  {
    id: "P0-DETACHED-HEARTBEAT",
    criticality: "P0",
    title: "Worker heartbeat is fire-and-forget void promise",
    domain: "Heartbeat",
    evidence: ["lib/work-queue/worker.ts:73-83"],
    impact: "double_execution",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-AUTOMATION-FIRE-AND-FORGET-PERSIST",
    criticality: "P1",
    title: "Automation persist scheduled via void persistDurableDomain",
    domain: "Automation",
    evidence: [
      "lib/automations/durable.ts:73-86",
      "lib/automation-platform/durable.ts:57",
    ],
    impact: "restart_inconsistency",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-MEMORY-FIRE-AND-FORGET-PERSIST",
    criticality: "P1",
    title: "Work/Personal Memory durable writes are detached",
    domain: "Memory",
    evidence: [
      "lib/work-memory/durable.ts:74-78",
      "lib/personal-memory/durable.ts:91-92",
    ],
    impact: "memory_loss",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-NOTIFICATION-DETACHED-DELIVERY",
    criticality: "P1",
    title: "LINE/WebPush delivery is void deliver*WithAck",
    domain: "Notification",
    evidence: ["lib/notifications/service.ts:141-213"],
    impact: "restart_inconsistency",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-OAUTH-TOKEN-REFRESH-DETACHED",
    criticality: "P1",
    title: "OAuth token refresh persistence is fire-and-forget",
    domain: "OAuthConnection",
    evidence: [
      "lib/integrations/x/token-manager.ts:90-92",
      "lib/integrations/google/token-manager.ts:87-89",
      "lib/integrations/x/oauth-service.ts:159-178",
    ],
    impact: "recovery_impossible",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-METRICS-PROCESS-ONLY",
    criticality: "P1",
    title: "Memory-apply / many monitoring counters are process-memory only",
    domain: "Metrics",
    evidence: [
      "lib/memory-apply/metrics.ts:33-47",
      "lib/owner/monitoring/store.ts:17-73",
    ],
    impact: "metrics_loss",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-SCHEDULE-TICK-MEMORY",
    criticality: "P1",
    title: "V2 scheduler due list depends on process-resident automations",
    domain: "Schedule",
    evidence: [
      "lib/automation-platform/schedule/due-tick.ts",
      "lib/automation-platform/repository/memory-store.ts:74-91",
    ],
    impact: "schedule_miss",
    restartRisk: true,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P1-RETRY-SCHEDULE-LOST",
    criticality: "P1",
    title: "Retry schedule lost if stored only in memory fallback job store",
    domain: "Retry",
    evidence: ["lib/jobs/job-store.ts:49-56", "lib/work-queue/retry.ts"],
    impact: "recovery_impossible",
    restartRisk: true,
    multiInstanceRisk: false,
    migrationTarget: true,
  },
  {
    id: "P2-LOCALSTORAGE-PROFILE-ONBOARDING",
    criticality: "P2",
    title: "User profile / onboarding / first-experience prefs use localStorage",
    domain: "FirstExperience",
    evidence: [
      "lib/user-profile/store.ts:112-148",
      "lib/onboarding/store.ts",
      "lib/first-experience/run.ts:32-49",
    ],
    impact: "ui_inconsistency",
    restartRisk: false,
    multiInstanceRisk: false,
    migrationTarget: true,
  },
  {
    id: "P2-PROJECTS-LOCALSTORAGE-FALLBACK",
    criticality: "P2",
    title: "Projects repository can use localStorage as backend/cache",
    domain: "DashboardAggregation",
    evidence: [
      "lib/projects/repositories/local-storage-repository.ts",
      "lib/supabase/env.ts:62-88",
      "lib/dashboard/use-dashboard-home.ts:64-65",
    ],
    impact: "cache_inconsistency",
    restartRisk: false,
    multiInstanceRisk: true,
    migrationTarget: true,
  },
  {
    id: "P2-THEME-SESSION-CACHE",
    criticality: "P2",
    title: "Theme / session draft pointers in browser storage (acceptable UI cache)",
    domain: "CrossCutting",
    evidence: [
      "lib/theme/storage.ts",
      "lib/automation-platform/client.ts:306-335",
      "lib/workspace/work-request-payload.ts:104-116",
    ],
    impact: "noncritical_history_loss",
    restartRisk: false,
    multiInstanceRisk: false,
    migrationTarget: false,
  },
] as const;

export function findingsByCriticality(level: FindingRecord["criticality"]) {
  return DURABLE_SOT_FINDINGS.filter((f) => f.criticality === level);
}
