import type { MigrationTarget } from "./types";

/**
 * DB migration targets for Durable SoT (planning only — no schema applied here).
 */
export const MIGRATION_TARGETS: readonly MigrationTarget[] = [
  {
    domain: "Job",
    currentStorage: "mixed",
    targetStorage: "Postgres atlas_work_queue_jobs (mandatory prod)",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "operational + audit window (90d+)",
    rollbackDifficulty: "high",
    priority: "P0",
    rationale: "File/memory fallback loses work on restart/multi-instance.",
  },
  {
    domain: "Run",
    currentStorage: "mixed",
    targetStorage: "Postgres atlas_automation_runs (or harden durable-domain await)",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: true,
    retention: "per applyRunRetentionPolicy + longer evidence retention",
    rollbackDifficulty: "high",
    priority: "P0",
    rationale: "V2 memory Map is live SoT for runs/idempotency/occurrence.",
  },
  {
    domain: "Step",
    currentStorage: "mixed",
    targetStorage: "Postgres atlas_work_queue_steps",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "with parent job",
    rollbackDifficulty: "medium",
    priority: "P0",
    rationale: "Step progress must survive crash for safe resume.",
  },
  {
    domain: "Lease",
    currentStorage: "mixed",
    targetStorage: "Postgres lease columns only",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: true,
    ttlRequired: true,
    retention: "lease TTL via lease_expires_at",
    rollbackDifficulty: "medium",
    priority: "P0",
    rationale: "File mutex is not multi-instance safe.",
  },
  {
    domain: "Heartbeat",
    currentStorage: "mixed",
    targetStorage: "Postgres heartbeat_at (awaited or batched durable)",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: false,
    uniqueConstraintRequired: false,
    transactionRequired: false,
    ttlRequired: true,
    retention: "overwrite in place",
    rollbackDifficulty: "low",
    priority: "P0",
    rationale: "Detached heartbeat causes false stuck / double lease.",
  },
  {
    domain: "Idempotency",
    currentStorage: "mixed",
    targetStorage: "DB unique indexes (runs, jobs, external actions)",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: true,
    retention: "TTL for ephemeral keys; permanent for external action receipts",
    rollbackDifficulty: "medium",
    priority: "P0",
    rationale: "Process Map idempotency cannot prevent cross-instance duplicates.",
  },
  {
    domain: "CompletionEvidence",
    currentStorage: "mixed",
    targetStorage: "DB evidence columns / outbox linked to job+run",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "long-term audit",
    rollbackDifficulty: "high",
    priority: "P0",
    rationale: "Evidence must precede completed; survive restart.",
  },
  {
    domain: "ExternalAction",
    currentStorage: "mixed",
    targetStorage: "DB external_action_attempts + provider idempotency",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "long-term",
    rollbackDifficulty: "high",
    priority: "P0",
    rationale: "Prevent duplicate side effects after crash/retry.",
  },
  {
    domain: "Schedule",
    currentStorage: "mixed",
    targetStorage: "DB schedule + occurrence reservation",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "with automation lifetime",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Due-tick memory lists miss/double across instances.",
  },
  {
    domain: "Occurrence",
    currentStorage: "mixed",
    targetStorage: "DB unique occurrence_key",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "with runs",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "V2 occurrenceKeys Map is process-local.",
  },
  {
    domain: "Retry",
    currentStorage: "mixed",
    targetStorage: "Postgres retry_at/attempt only",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: true,
    ttlRequired: false,
    retention: "with job",
    rollbackDifficulty: "low",
    priority: "P1",
    rationale: "Memory fallback drops retry schedules.",
  },
  {
    domain: "Recovery",
    currentStorage: "mixed",
    targetStorage: "DB reclaim based on lease + evidence",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: true,
    ttlRequired: false,
    retention: "operational",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Recovery needs durable job/lease truth.",
  },
  {
    domain: "Artifact",
    currentStorage: "mixed",
    targetStorage: "atlas_deliverable_files + Storage (awaited)",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "user data retention policy",
    rollbackDifficulty: "high",
    priority: "P1",
    rationale: "void persist creates crash window after generate.",
  },
  {
    domain: "Notification",
    currentStorage: "mixed",
    targetStorage: "DB outbox + atlas_user_state / DLQ tables",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: true,
    retention: "notifications TTL + DLQ retention",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Detached delivery + memory hot store.",
  },
  {
    domain: "Memory",
    currentStorage: "mixed",
    targetStorage: "atlas_user_state (awaited) or dedicated tables",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: true,
    ttlRequired: false,
    retention: "user lifetime",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Fire-and-forget persist loses recent writes.",
  },
  {
    domain: "Metrics",
    currentStorage: "mixed",
    targetStorage: "atlas_reliability_events + aggregated metrics tables",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: false,
    ttlRequired: true,
    retention: "30-90d rollups",
    rollbackDifficulty: "low",
    priority: "P1",
    rationale: "Process counters disappear every deploy.",
  },
  {
    domain: "OAuthConnection",
    currentStorage: "mixed",
    targetStorage: "Existing OAuth tables (await refresh persist)",
    migrationRequired: true,
    schemaRequired: false,
    repositoryRequired: false,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "while connected",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Detached token persist can brick connections after refresh.",
  },
  {
    domain: "Approval",
    currentStorage: "mixed",
    targetStorage: "DB run status + approval records",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: true,
    transactionRequired: true,
    ttlRequired: false,
    retention: "with run",
    rollbackDifficulty: "medium",
    priority: "P1",
    rationale: "Follows Run SoT migration.",
  },
  {
    domain: "FirstExperience",
    currentStorage: "browser_storage",
    targetStorage: "user durable prefs domain / profile table",
    migrationRequired: true,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: false,
    ttlRequired: false,
    retention: "user lifetime",
    rollbackDifficulty: "low",
    priority: "P2",
    rationale: "localStorage not server SoT; multi-device inconsistent.",
  },
  {
    domain: "DashboardAggregation",
    currentStorage: "derived",
    targetStorage: "keep derived; ensure underlying projects SoT is DB",
    migrationRequired: false,
    schemaRequired: false,
    repositoryRequired: false,
    uniqueConstraintRequired: false,
    transactionRequired: false,
    ttlRequired: false,
    retention: "n/a",
    rollbackDifficulty: "low",
    priority: "P2",
    rationale: "Fix project backend; aggregation stays computed.",
  },
  {
    domain: "SavedMinutes",
    currentStorage: "derived",
    targetStorage: "optional metrics table if product requires durable KPI",
    migrationRequired: false,
    schemaRequired: true,
    repositoryRequired: true,
    uniqueConstraintRequired: false,
    transactionRequired: false,
    ttlRequired: true,
    retention: "rollups",
    rollbackDifficulty: "low",
    priority: "P2",
    rationale: "Currently null-derived; no SoT to migrate yet.",
  },
] as const;

export const RECOMMENDED_MIGRATION_ORDER: ReadonlyArray<{
  order: number;
  domain: string;
  reason: string;
}> = [
  {
    order: 1,
    domain: "Job / Run / Step",
    reason:
      "All completion, lease, and evidence hang off job/run/step identity. V2 memory runs + WQ file fallback are the largest loss/duplication surface.",
  },
  {
    order: 2,
    domain: "Lease / Heartbeat",
    reason:
      "Without durable lease truth, multi-worker reclaim doubles execution of the jobs just migrated.",
  },
  {
    order: 3,
    domain: "Idempotency",
    reason:
      "DB unique keys must exist before retry/recovery is made aggressive, or duplicates increase.",
  },
  {
    order: 4,
    domain: "Completion Evidence + External Action outbox",
    reason:
      "Prevents false completed and external duplicates once retries are reliable.",
  },
  {
    order: 5,
    domain: "Scheduler / Occurrence",
    reason:
      "Depends on durable job enqueue + occurrence unique; otherwise tick storms recreate work.",
  },
  {
    order: 6,
    domain: "Retry / Recovery",
    reason:
      "Safe only after evidence + idempotency exist so reclaim cannot re-fire side effects blindly.",
  },
  {
    order: 7,
    domain: "Artifact / Storage metadata",
    reason:
      "Link artifacts to durable job/run evidence; remove void-persist crash window.",
  },
  {
    order: 8,
    domain: "Notification outbox",
    reason:
      "Delivery can be eventually consistent once job completion is durable and idempotent.",
  },
  {
    order: 9,
    domain: "Memory",
    reason:
      "User value high but not on the critical external-action path; await persist after core queue SoT.",
  },
  {
    order: 10,
    domain: "Metrics / Monitoring / First Experience",
    reason:
      "Observability and UX prefs after production work integrity is guaranteed.",
  },
] as const;

/** Concrete Phase 1-2 targets (next stage only — not implemented here). */
export const PHASE_1_2_TARGETS = [
  "Eliminate production Work Queue file fallback (fail-closed to Postgres)",
  "Replace V2 __atlasAutomationPlatformStore runs/occurrence/idempotency with DB repository",
  "Await (or transactional outbox) for run/job durable writes on enqueue and terminal transitions",
  "Durable external_action attempt records before provider calls",
  "Baseline diff gate already tracks new memory/file/detached regressions",
] as const;
