/**
 * Scheduler Production Audit inventory — facts derived from main repo code/config.
 * Phase 2-1: documentation + regression detection only.
 */

import type {
  CronDefinition,
  NextRunAtPath,
  RiskRegisterItem,
  SchedulerAuditSnapshot,
  SchedulerEntryPoint,
  SecretAuditRow,
  SotRow,
} from "./types";

/** Active vercel.json cron schedule (Hobby-safe daily). */
export const ACTIVE_VERCEL_CRON_SCHEDULE = "0 0 * * *";
export const ACTIVE_VERCEL_CRON_PATH = "/api/automations/tick";
export const PRO_TEMPLATE_CRON_SCHEDULE = "* * * * *";
export const GITHUB_MINUTE_CRON_SCHEDULE = "* * * * *";
export const TICK_ROUTE = "/api/automations/tick";
export const DRAIN_ROUTE = "/api/worker/drain";

export const SCHEDULER_ENTRY_POINTS: SchedulerEntryPoint[] = [
  {
    id: "vercel-cron-hobby-daily",
    file: "vercel.json",
    route: TICK_ROUTE,
    functionName: "Vercel Cron → POST/GET tick",
    caller: "Vercel platform (Production deployments)",
    executionEnvironment: "vercel_production",
    frequency: ACTIVE_VERCEL_CRON_SCHEDULE,
    authentication: "Vercel injects Authorization: Bearer $CRON_SECRET (platform)",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: "unconfirmed",
    previewReachable: false,
    duplicateRisk: "Low if occurrenceKey unique; overlap with GH Actions possible",
    missedRunRisk: "HIGH for sub-daily schedules — daily only",
    notes:
      "Preview: Vercel Cron does not run on Preview by default (platform). Production fire = UNCONFIRMED without Vercel logs.",
  },
  {
    id: "vercel-cron-pro-template",
    file: "vercel.cron.pro.json",
    route: TICK_ROUTE,
    functionName: "Template only — not active until copied into vercel.json",
    caller: "ops (manual copy)",
    executionEnvironment: "vercel_production",
    frequency: PRO_TEMPLATE_CRON_SCHEDULE,
    authentication: "Same as active cron once wired",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: false,
    previewReachable: false,
    duplicateRisk: "N/A until activated",
    missedRunRisk: "N/A until activated",
    notes: "Hobby rejects minute schedules; template documents Pro path.",
  },
  {
    id: "github-actions-minute-scheduler",
    file: ".github/workflows/minute-scheduler.yml",
    route: TICK_ROUTE,
    functionName: "curl POST with Bearer CRON_SECRET",
    caller: "GitHub Actions schedule + workflow_dispatch",
    executionEnvironment: "github_actions",
    frequency: GITHUB_MINUTE_CRON_SCHEDULE,
    authentication: "Authorization: Bearer ${{ secrets.CRON_SECRET }}",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: "unconfirmed",
    previewReachable: false,
    duplicateRisk:
      "concurrency group minute-scheduler cancel-in-progress:false — overlaps possible; occurrence dedupe mitigates double jobs",
    missedRunRisk:
      "HIGH if CRON_SECRET or ATLAS_APP_URL GitHub secrets missing (workflow exits 1). GH schedule can delay.",
    notes: "Intended production minute path without Vercel Pro.",
  },
  {
    id: "api-automations-tick",
    file: "app/api/automations/tick/route.ts",
    route: TICK_ROUTE,
    functionName: "POST/GET → processWorkQueueTick + V2 due-tick + X + reports",
    caller: "Vercel Cron / GH Actions / Owner UI / manual curl",
    executionEnvironment: "vercel_any",
    frequency: "on invoke",
    authentication:
      "authorizeAutomationTick: CRON_SECRET (timing-safe) or Owner (prod); any signed-in (non-prod)",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "Mitigated by occurrenceKey/idempotency; concurrent ticks still load",
    missedRunRisk: "Depends on invoker frequency",
    notes: "Clerk public matcher; route still requires secret/owner/session.",
  },
  {
    id: "api-worker-drain",
    file: "app/api/worker/drain/route.ts",
    route: DRAIN_ROUTE,
    functionName: "POST/GET → drainWorkQueue",
    caller: "Intended cron/ops; also embedded in processWorkQueueTick",
    executionEnvironment: "vercel_any",
    frequency: "on invoke",
    authentication: "authorizeAutomationTick in handler",
    dbAccess: true,
    queueAccess: true,
    createsRun: false,
    createsJob: false,
    productionReachable: false,
    previewReachable: false,
    duplicateRisk: "Lease protects double process",
    missedRunRisk:
      "Independent CRON_SECRET drain blocked: route NOT in public-routes → Clerk middleware 401 before handler",
    notes: "Production drain currently relies on being called inside /api/automations/tick.",
  },
  {
    id: "owner-manual-tick-ui",
    file: "components/owner/automation-execution-log-panel.tsx",
    route: TICK_ROUTE,
    functionName: "fetch tick",
    caller: "Owner console button",
    executionEnvironment: "browser_client",
    frequency: "manual",
    authentication: "Owner session cookie",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "Can race with cron; occurrence dedupe",
    missedRunRisk: "N/A (manual)",
    notes: "Manual recovery / verification path.",
  },
  {
    id: "client-tickAutomations",
    file: "lib/automations/client.ts",
    route: TICK_ROUTE,
    functionName: "tickAutomations",
    caller: "API consumers (no setInterval found)",
    executionEnvironment: "browser_client",
    frequency: "manual/on-demand only",
    authentication: "session cookies",
    dbAccess: true,
    queueAccess: true,
    createsRun: true,
    createsJob: true,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "Same as tick",
    missedRunRisk: "Not a production scheduler",
    notes: "No automatic client interval tick found in repo.",
  },
  {
    id: "processWorkQueueTick",
    file: "lib/work-queue/tick.ts",
    route: null,
    functionName: "processWorkQueueTick",
    caller: "tick route / tests / processDueAutomations",
    executionEnvironment: "in_process",
    frequency: "on call",
    authentication: "N/A (server)",
    dbAccess: true,
    queueAccess: true,
    createsRun: false,
    createsJob: true,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "occurrenceKey unique constraint",
    missedRunRisk: "Batch limit WORK_QUEUE_SCHEDULER_BATCH (50)",
    notes: "Hydrates V1 owners via global index; advances nextRun after enqueue.",
  },
  {
    id: "processDueScheduledAutomationsV2",
    file: "lib/automation-platform/schedule/due-tick.ts",
    route: null,
    functionName: "processDueScheduledAutomationsV2",
    caller: "tick route (hydrateUserIds omitted)",
    executionEnvironment: "in_process",
    frequency: "on tick",
    authentication: "N/A",
    dbAccess: true,
    queueAccess: false,
    createsRun: true,
    createsJob: false,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "schedule_occurrence_key unique (when DB migrated)",
    missedRunRisk:
      "HIGH on cold start: no V2 global owner index; tick does not pass hydrateUserIds → often 0 due",
    notes: "Feature-flagged automation_v2_enabled.",
  },
  {
    id: "v2-to-v1-bridge",
    file: "lib/automation-platform/bridge/v2-to-v1-scheduler.ts",
    route: null,
    functionName: "syncV2ToV1Scheduler",
    caller: "V2 create/update bridge",
    executionEnvironment: "in_process",
    frequency: "on sync",
    authentication: "N/A",
    dbAccess: true,
    queueAccess: false,
    createsRun: false,
    createsJob: false,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "Shadow V1 registration",
    missedRunRisk: "Execution still depends on V1 tick path",
    notes: "Not a tick; registers V1 shadow for schedule execution.",
  },
  {
    id: "memory-apply-scheduler-defaults",
    file: "lib/memory-apply/scheduler.ts",
    route: null,
    functionName: "resolveSchedulerMemoryDefaults",
    caller: "bridge/create paths",
    executionEnvironment: "in_process",
    frequency: "on create",
    authentication: "N/A",
    dbAccess: false,
    queueAccess: false,
    createsRun: false,
    createsJob: false,
    productionReachable: true,
    previewReachable: true,
    duplicateRisk: "none",
    missedRunRisk: "none",
    notes: "Timezone/notify defaults only — does not tick.",
  },
];

export const CRON_DEFINITIONS: CronDefinition[] = [
  {
    id: "vercel-json-daily",
    sourceFile: "vercel.json",
    activeInRepo: true,
    path: ACTIVE_VERCEL_CRON_PATH,
    schedule: ACTIVE_VERCEL_CRON_SCHEDULE,
    httpMethod: "GET/POST (route exports both; Vercel Cron typically GET)",
    secretUsage: "CRON_SECRET via Authorization Bearer (platform injection claimed in .env.local.example)",
    productionOnly: "Vercel Cron runs on Production deployments (platform default)",
    previewBehavior: "Does not run on Preview by default (platform; not overridden in repo)",
    retryBehavior: "UNCONFIRMED — Vercel Cron retry policy not configured in-repo",
    failureHandling: "Tick records recordCronTickOutcome(false); returns 5xx/401/503 JSON",
    measuredEvidence: "NONE in repo — no live Vercel log artifacts committed",
    notes: "Hobby-safe daily fallback. Implicit daily dependency for sub-daily schedules unless GH Actions live.",
  },
  {
    id: "vercel-cron-pro-template",
    sourceFile: "vercel.cron.pro.json",
    activeInRepo: false,
    path: ACTIVE_VERCEL_CRON_PATH,
    schedule: PRO_TEMPLATE_CRON_SCHEDULE,
    httpMethod: "GET/POST",
    secretUsage: "Same CRON_SECRET once activated",
    productionOnly: "Intended production after Pro upgrade + copy into vercel.json",
    previewBehavior: "N/A",
    retryBehavior: "UNCONFIRMED",
    failureHandling: "Same as tick route",
    measuredEvidence: "NONE — template not active",
    notes: "Must not be confused with live production cron.",
  },
  {
    id: "github-actions-minute",
    sourceFile: ".github/workflows/minute-scheduler.yml",
    activeInRepo: true,
    path: ACTIVE_VERCEL_CRON_PATH,
    schedule: GITHUB_MINUTE_CRON_SCHEDULE,
    httpMethod: "POST",
    secretUsage: "GitHub secrets CRON_SECRET + ATLAS_APP_URL required (fail-closed)",
    productionOnly: "Targets ATLAS_APP_URL (ops-defined; typically production)",
    previewBehavior: "Not wired to Preview URLs in workflow",
    retryBehavior: "Job fails on curl -f; no custom retry loop; GH may re-run schedule next minute",
    failureHandling: "Workflow exits 1 if secrets missing or HTTP error",
    measuredEvidence: "NONE in repo — Actions run history is external UNCONFIRMED",
    notes: "Platform schedule delay possible; concurrency cancel-in-progress:false.",
  },
];

export const SECRET_AUDIT: SecretAuditRow[] = [
  {
    key: "CRON_SECRET",
    required: true,
    buildTime: false,
    runtime: true,
    missingBehavior:
      "Production tick → 503 CRON_SECRET is not configured (fail-closed). Non-prod signed-in users may still tick.",
    misconfiguredBehavior: "Wrong secret → 401 unless Owner session in production",
    logExposure: "Compared via timingSafeEqual; not logged in tick-auth",
    rotatable: true,
    productionConfiguredConfirmable:
      "Owner env-status registry marks required; actual Vercel dashboard value UNCONFIRMED from repo",
    notes: "Also required as GitHub Actions secret for minute workflow.",
  },
  {
    key: "ATLAS_APP_URL",
    required: true,
    buildTime: false,
    runtime: false,
    missingBehavior: "GitHub Actions minute-scheduler exits 1",
    misconfiguredBehavior: "curl hits wrong host; tick may miss production",
    logExposure: "Used as curl URL in Actions logs",
    rotatable: true,
    productionConfiguredConfirmable: "GitHub secrets UI only — UNCONFIRMED from repo",
    notes: "Not in .env.local.example; not used by Next.js runtime tick itself.",
  },
  {
    key: "NEXT_PUBLIC_APP_URL",
    required: true,
    buildTime: true,
    runtime: true,
    missingBehavior: "URL generation fallbacks (SITE_URL / VERCEL_URL); not used by tick auth",
    misconfiguredBehavior: "Wrong absolute URLs for Push/Stripe — not scheduler tick",
    logExposure: "Public by design",
    rotatable: true,
    productionConfiguredConfirmable: "UNCONFIRMED from repo",
    notes: "Not a scheduler secret; listed for Preview/Production URL audit completeness.",
  },
  {
    key: "ENABLE_SCHEDULED_CRON",
    required: false,
    buildTime: false,
    runtime: true,
    missingBehavior: "Default enabled (any value except false)",
    misconfiguredBehavior: "false → auth ok but due work skipped with skipped:true JSON (still 200)",
    logExposure: "Returned in response reason",
    rotatable: true,
    productionConfiguredConfirmable: "UNCONFIRMED",
    notes: "Kill-switch after auth — not an auth secret.",
  },
  {
    key: "INTERNAL_API_SECRET",
    required: false,
    buildTime: false,
    runtime: false,
    missingBehavior: "N/A — key does not exist in codebase",
    misconfiguredBehavior: "N/A",
    logExposure: "N/A",
    rotatable: false,
    productionConfiguredConfirmable: "N/A",
    notes: "No Scheduler-dedicated INTERNAL_API_SECRET found.",
  },
  {
    key: "DATABASE_URL / POSTGRES_URL / SUPABASE_DB_URL / DIRECT_URL",
    required: false,
    buildTime: false,
    runtime: true,
    missingBehavior: "Work-queue falls back to file store (.data)",
    misconfiguredBehavior: "Enqueue/drain fails or uses wrong DB",
    logExposure: "Should not be logged; connection errors may surface messages",
    rotatable: true,
    productionConfiguredConfirmable: "UNCONFIRMED; migration apply UNCONFIRMED",
    notes: "ATLAS_WORK_QUEUE_FORCE_FILE=true forces file store (CI).",
  },
];

export const NEXT_RUN_AT_PATHS: NextRunAtPath[] = [
  {
    id: "v1-create",
    triggerCase: "Schedule create",
    functionName: "computeNextRunIso via domain create",
    file: "lib/automations/domain.ts",
    timezoneSource: "schedule.timezone || Asia/Tokyo",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "preset math; cron string stored but not SoT",
  },
  {
    id: "v1-update-enable",
    triggerCase: "Schedule update / enable",
    functionName: "computeNextRunIso",
    file: "lib/automations/repositories/server-automation-repository.ts",
    timezoneSource: "schedule.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Disable clears nextRun; enable recomputes from now",
  },
  {
    id: "v1-pause-resume",
    triggerCase: "Pause / Resume (enabled=false/true)",
    functionName: "setEnabledForUser → nextRun null / computeNextRunIso",
    file: "lib/automations/pause-resume.test.ts + service",
    timezoneSource: "schedule.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Pause = disable; no separate paused column on V1 tick path",
  },
  {
    id: "v1-skip-next",
    triggerCase: "Skip next",
    functionName: "computeSkipNextRunIso",
    file: "lib/work-queue/schedule-math.ts + control.ts",
    timezoneSource: "schedule.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Advances from currentNextRun + 60s",
  },
  {
    id: "v1-run-complete",
    triggerCase: "Run complete (sync path)",
    functionName: "computeNextRunIso(schedule, completedAt)",
    file: "lib/automations/run-automation.ts",
    timezoneSource: "schedule.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Legacy sync completion path",
  },
  {
    id: "v1-due-tick-advance",
    triggerCase: "Due tick after enqueue/dedupe",
    functionName: "advanceNextRun → computeNextRunIso(schedule, now)",
    file: "lib/work-queue/tick.ts + scheduler.ts",
    timezoneSource: "schedule.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Always advances even on dedupe — no backlog replay",
  },
  {
    id: "v1-core-math",
    triggerCase: "Daily/weekly/monthly + DST",
    functionName: "computeNextRun / computeNextFromPreset",
    file: "lib/automations/schedule.ts",
    timezoneSource: "IANA via Intl + offset recompute",
    clientOrServer: "server",
    persistsToDb: false,
    notes: "Pure function; month-end clamps dayOfMonth",
  },
  {
    id: "v2-create-update",
    triggerCase: "V2 create/update/activate",
    functionName: "computeNextRunIsoFromTrigger",
    file: "lib/automation-platform/schedule/compute.ts + service",
    timezoneSource: "trigger.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Frequencies: once/daily/weekly/monthly/weekdays/month_end/custom_days",
  },
  {
    id: "v2-due-tick",
    triggerCase: "V2 due tick enqueue / dedupe / failure",
    functionName: "computeNextRunIsoFromTrigger after enqueue",
    file: "lib/automation-platform/schedule/due-tick.ts",
    timezoneSource: "trigger.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Advances on dedupe AND enqueue failure (can skip slot on transient errors)",
  },
  {
    id: "v2-enqueue-run",
    triggerCase: "V2 schedule run create",
    functionName: "computeNextRunIsoFromTrigger(scheduledFor)",
    file: "lib/automation-platform/service/automation-service.ts",
    timezoneSource: "trigger.timezone",
    clientOrServer: "server",
    persistsToDb: true,
    notes: "Advances nextRunAt inside enqueueRun when created",
  },
  {
    id: "form-client-preview",
    triggerCase: "UI form schedule label/preview",
    functionName: "form-utils schedule helpers",
    file: "lib/automations/form-utils.ts",
    timezoneSource: "form state",
    clientOrServer: "mixed",
    persistsToDb: false,
    notes: "Client display; server recomputes on persist — duplicate display risk only",
  },
];

export const SCHEDULER_SOT: SotRow[] = [
  {
    state: "Schedule definition (V1)",
    sot: "mixed",
    detail:
      "Durable: Supabase atlas_user_state domain atlasAutomations. Process: serverAutomationRepository Map hydrated per user.",
  },
  {
    state: "nextRun (V1)",
    sot: "mixed",
    detail: "Stored on automation row in durable user state + memory cache; advanced server-side on tick/create/enable.",
  },
  {
    state: "nextRunAt (V2)",
    sot: "mixed",
    detail:
      "Durable atlasAutomationsV2 + memory-store Maps. Cron discovery incomplete without hydrateUserIds.",
  },
  {
    state: "lastRunAt / lastSuccessAt / lastFailureAt (automation)",
    sot: "mixed",
    detail: "Updated on run paths in durable state when execution records outcomes; not a separate scheduler ledger.",
  },
  {
    state: "occurrence (V1 work-queue)",
    sot: "mixed",
    detail:
      "Postgres unique(automation_id, occurrence_key) OR file-store JSON. Prefer PG when DATABASE_URL present.",
  },
  {
    state: "occurrence (V2 runs)",
    sot: "mixed",
    detail: "Partial unique index on schedule_occurrence_key when migration applied + memory maps.",
  },
  {
    state: "Scheduler health lastSuccessAt (work-queue metrics)",
    sot: "mixed",
    detail:
      "Postgres store: process memory field only (NOT SQL). File store: JSON meta. Multi-instance PG metrics unreliable.",
  },
  {
    state: "Cron tick monitor (owner monitoring)",
    sot: "mixed",
    detail: "globalThis bucket + async persist to Supabase __atlas_monitoring__ (debounced).",
  },
  {
    state: "Scheduler history (durable ledger of every fire)",
    sot: "undefined",
    detail: "No durable Scheduler History SoT for every tick fire. Work-queue logs + in-memory cron debug only.",
  },
  {
    state: "Scheduler metrics (avg/p95 delay)",
    sot: "mixed",
    detail: "In-process histograms on PG store; file store persists meta. Not a cross-instance durable time series.",
  },
];

export const RISK_REGISTER: RiskRegisterItem[] = [
  {
    id: "p0-minute-path-unconfirmed",
    severity: "P0",
    title: "分単位本番実行が未証明（daily cron 暗黙依存）",
    category: "miss",
    currentBehavior:
      "vercel.json is daily; minute path is GH Actions requiring secrets UNCONFIRMED. Sub-daily schedules miss without Actions.",
    requiredFix:
      "Confirm GH secrets + Actions green history OR activate Pro minute cron; prove live fires with durable history.",
    phase22Candidate: true,
  },
  {
    id: "p0-v2-due-tick-hydration",
    severity: "P0",
    title: "V2 due tick が cold start で due を見逃す",
    category: "miss",
    currentBehavior:
      "processDueScheduledAutomationsV2 scans memory only; tick route passes no hydrateUserIds; no V2 global owner index.",
    requiredFix: "Hydrate V2 owners on tick (global index) before due scan.",
    phase22Candidate: true,
  },
  {
    id: "p0-advance-before-job-crash",
    severity: "P0",
    title: "Job作成失敗後も nextRun が進むと実行漏れ",
    category: "miss",
    currentBehavior:
      "enqueueDueAutomations always advanceNextRun after enqueue attempt; store.enqueue should return existing on dup. Hard failure mid-loop can leave partial advances.",
    requiredFix: "Transactional enqueue+advance or advance only after durable job create success.",
    phase22Candidate: true,
  },
  {
    id: "p0-v2-advance-on-failure",
    severity: "P0",
    title: "V2 enqueue失敗時も nextRunAt を進めてスロットを飛ばす",
    category: "miss",
    currentBehavior: "due-tick.ts catch advances nextRunAt to avoid tight loops.",
    requiredFix: "Distinguish transient vs permanent errors; only advance on permanent/dedupe.",
    phase22Candidate: true,
  },
  {
    id: "p1-drain-not-public",
    severity: "P1",
    title: "/api/worker/drain が CRON_SECRET 単独で到達不可",
    category: "auth",
    currentBehavior: "Not in public-routes; Clerk middleware returns 401 before handler auth.",
    requiredFix: "Add to public API matchers OR remove independent drain claim from docs; keep drain inside tick.",
    phase22Candidate: true,
  },
  {
    id: "p1-no-scheduler-history",
    severity: "P1",
    title: "Scheduler History 未実装（本番実測証拠が残らない）",
    category: "evidence",
    currentBehavior: "In-process cron debug + monitoring tick state; no durable per-fire history table.",
    requiredFix: "Durable scheduler_history with scheduledAt/executedAt/delay/outcome.",
    phase22Candidate: true,
  },
  {
    id: "p1-pg-metrics-memory",
    severity: "P1",
    title: "PG work-queue schedulerLastSuccessAt が process memory",
    category: "health",
    currentBehavior: "recordSchedulerSuccess updates in-memory field only on PostgresStore.",
    requiredFix: "Persist scheduler heartbeat to SQL for multi-instance health.",
    phase22Candidate: true,
  },
  {
    id: "p1-secrets-unconfirmed",
    severity: "P1",
    title: "Production CRON_SECRET / GH ATLAS_APP_URL 設定がリポジトリから確認不可",
    category: "secrets",
    currentBehavior: "Code fail-closed when missing; live configured state UNCONFIRMED.",
    requiredFix: "Ops checklist + Owner env-status screenshot / Actions green proof.",
    phase22Candidate: true,
  },
  {
    id: "p1-preview-prod-divergence",
    severity: "P1",
    title: "Preview では Cron 不発火・非prodは signed-in 誰でも tick 可",
    category: "preview_prod",
    currentBehavior: "Auth differs by isAtlasProduction(); Preview has no platform cron.",
    requiredFix: "Document + optional Preview kill-switch default; separate Preview secrets.",
    phase22Candidate: true,
  },
  {
    id: "p1-claim-slot-unused",
    severity: "P1",
    title: "claimAutomationTickSlot が本番 tick から未使用",
    category: "duplicate",
    currentBehavior: "Implemented and tested but not called by processWorkQueueTick.",
    requiredFix: "Wire claim or delete dead path; rely explicitly on occurrence unique.",
    phase22Candidate: true,
  },
  {
    id: "p1-hundred-proof-inprocess",
    severity: "P1",
    title: "100回実測は in-process Vitest であり本番Scheduler実測ではない",
    category: "evidence",
    currentBehavior: "writeSchedulerHundredProof note explicitly says not live Vercel cron.",
    requiredFix: "Live proof with durable history over wall-clock minutes.",
    phase22Candidate: true,
  },
  {
    id: "p2-metrics-gaps",
    severity: "P2",
    title: "missed/duplicate/stuck counts が横断時系列で不足",
    category: "health",
    currentBehavior: "Alerts exist for backlog/stuck/success rate; no durable missed/duplicate counters history.",
    requiredFix: "Export counters to Scheduler History + Owner dashboard time series.",
    phase22Candidate: true,
  },
  {
    id: "p2-duplicate-nextrun-impl",
    severity: "P2",
    title: "V1/V2 nextRun 計算の二重実装",
    category: "nextRunAt",
    currentBehavior: "lib/automations/schedule.ts and lib/automation-platform/schedule/compute.ts both implement TZ math.",
    requiredFix: "Document SoT per generation; eventually share timezone primitives only (no big-bang).",
    phase22Candidate: false,
  },
];

export const HEALTH_INVENTORY: SchedulerAuditSnapshot["healthInventory"] = {
  last_tick: "partial",
  last_success: "partial",
  last_failure: "partial",
  due_count: "partial",
  queue_count: "implemented",
  schedule_delay: "partial",
  missed_count: "unimplemented",
  duplicate_count: "partial",
  stuck_count: "implemented",
  average_delay: "partial",
  p95_delay: "partial",
  alert: "implemented",
};

export const UNCONFIRMED: string[] = [
  "Whether CRON_SECRET is set in Vercel Production/Preview env",
  "Whether GitHub secrets CRON_SECRET and ATLAS_APP_URL are set for minute-scheduler.yml",
  "Whether Vercel Hobby/Pro plan is currently active for the project",
  "Whether Vercel Cron actually fires daily on Production (no log artifacts in repo)",
  "Whether supabase migration 20260802_atlas_work_queue.sql is applied in Production",
  "Vercel function region / maxDuration / concurrency for /api/automations/tick (not in vercel.json)",
  "Vercel Cron retry behavior on HTTP 5xx",
  "Live Preview deployment ENABLE_SCHEDULED_CRON value",
];

export function buildSchedulerAuditSnapshot(
  generatedAt: string = new Date().toISOString(),
): SchedulerAuditSnapshot {
  return {
    phase: "2-1",
    generatedAt,
    gitCommitHint: "main-audit-branch",
    verdict: {
      phasePass: true,
      schedulerFullyMapped: true,
      minuteProductionProven: false,
      rationale: [
        "All in-repo entry points, crons, secrets, nextRunAt paths, due-tick steps, and SoT classified from code.",
        "Minute production path exists as GH Actions workflow but secrets/live fires are UNCONFIRMED.",
        "100-run proof is in-process Vitest, not live Vercel cron.",
        "No Scheduler full rewrite performed in Phase 2-1.",
      ],
    },
    entryPoints: SCHEDULER_ENTRY_POINTS,
    crons: CRON_DEFINITIONS,
    secrets: SECRET_AUDIT,
    nextRunAtPaths: NEXT_RUN_AT_PATHS,
    sot: SCHEDULER_SOT,
    risks: RISK_REGISTER,
    healthInventory: HEALTH_INVENTORY,
    productionEvidence: {
      liveVercelCronHundredRuns: false,
      inProcessHundredProofExists: true,
      evidenceLocation:
        "/opt/cursor/artifacts/scheduler-production/scheduler-100-proof.json (generated by tests; not live)",
      note: "In-process proof must not be reported as production Scheduler measurement.",
    },
    unconfirmed: UNCONFIRMED,
  };
}
