import { randomUUID } from "crypto";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

import {
  buildUnifiedPreview,
  createArtifactRevision,
  listUnifiedArtifacts,
  registerArtifact,
} from "@/lib/artifact-platform";
import { getStoredDeliverableForUser } from "@/lib/deliverables/store";
import { classifyArtifactFailure } from "@/lib/artifact-durability/classify";
import { generateForCase } from "@/lib/artifact-durability/generate";
import { buildRevisionContent } from "@/lib/artifact-durability/revision-content";
import { validateStructure } from "@/lib/artifact-durability/structure";
import type {
  ArtifactCaseResult,
  ArtifactEvalCase,
} from "@/lib/artifact-durability/types";

export type RunCaseOptions = {
  userId: string;
  outDir: string;
  runRevision?: boolean;
  environment?: "local" | "production-http";
  /** Second user for cross-tenant access probe (must fail). */
  otherUserId?: string;
  /** 0..n for cycling revision edit kinds (text/table/image etc.). */
  revisionIndex?: number;
};

export async function runArtifactCase(
  c: ArtifactEvalCase,
  options: RunCaseOptions
): Promise<ArtifactCaseResult> {
  const requestId = `ad_${c.caseId}_${randomUUID().replace(/-/g, "").slice(0, 12)}`;
  const jobId = `adj_${randomUUID().replace(/-/g, "").slice(0, 12)}`;
  const startedAt = new Date().toISOString();
  const startedMs = Date.now();
  const log: string[] = [`start ${c.caseId} request_id=${requestId}`];

  let okGenerate = false;
  let okStructure = false;
  let okStorage = false;
  let okDb = false;
  let okPreview = false;
  let okDownload = false;
  let okRevision = false;
  let revisionAttempted = false;
  let crossUserLeak = false;
  let generateMs: number | null = null;
  let saveMs: number | null = null;
  let previewMs: number | null = null;
  let artifactId: string | null = null;
  let fileSize: number | null = null;
  let sha256: string | null = null;
  let structureChecks: ArtifactCaseResult["structureChecks"] = [];
  let failedStage: string | null = null;
  let failureReason: string | null = null;
  let developerCode: string | null = null;
  let finalStatus = "failed";
  const retryCount = 0;

  try {
    const g0 = Date.now();
    const file = await generateForCase(c);
    generateMs = Date.now() - g0;
    okGenerate = true;
    fileSize = file.buffer.byteLength;
    log.push(`generated bytes=${fileSize} ms=${generateMs}`);

    if (fileSize === 0) {
      failedStage = "generate";
      failureReason = "zero_byte";
      throw new Error("zero_byte");
    }

    // Persist binary evidence (not to repo)
    const binDir = join(options.outDir, "binaries", c.format);
    mkdirSync(binDir, { recursive: true });
    writeFileSync(join(binDir, `${c.caseId}.${c.format}`), file.buffer);

    const structure = await validateStructure(c.format, file);
    structureChecks = structure.checks;
    okStructure = structure.ok;
    sha256 = structure.sha256;
    log.push(`structure ok=${okStructure} sha=${sha256.slice(0, 12)}`);
    if (!okStructure) {
      failedStage = "structure";
      failureReason = structure.checks
        .filter((x) => !x.ok)
        .map((x) => x.name)
        .join(",");
      throw new Error(`structure_failed:${failureReason}`);
    }

    const s0 = Date.now();
    const registered = await registerArtifact({
      userId: options.userId,
      buffer: file.buffer,
      format: c.format,
      title: c.title,
      fileName: file.fileName,
      sourceContent: c.content,
      requestId,
      jobId,
      createdFrom: "artifact-durability",
    });
    saveMs = Date.now() - s0;
    artifactId = registered.id;
    okDb = Boolean(registered.id);
    okStorage = (registered.fileSize ?? 0) > 0;
    log.push(
      `registered id=${artifactId} saveMs=${saveMs} fileSize=${registered.fileSize} storageOk=${okStorage}`
    );

    const listed = await listUnifiedArtifacts({
      userId: options.userId,
      limit: 50,
    });
    const inList = listed.items.some((a) => a.id === artifactId);
    if (!inList) {
      log.push("warn: not in first page of list");
    }

    const p0 = Date.now();
    try {
      const preview = await buildUnifiedPreview({
        artifactId: artifactId!,
        userId: options.userId,
      });
      previewMs = Date.now() - p0;
      okPreview = Boolean(preview.ok);
      log.push(`preview ok=${okPreview} kind=${preview.kind} ms=${previewMs}`);
      if (!okPreview) {
        failedStage = "preview";
        failureReason = preview.message ?? "preview_failed";
      }
    } catch (error) {
      previewMs = Date.now() - p0;
      failedStage = "preview";
      failureReason = error instanceof Error ? error.message : String(error);
      log.push(`preview error: ${failureReason}`);
    }

    const stored = await getStoredDeliverableForUser(
      artifactId!,
      options.userId
    );
    okDownload = Boolean(stored?.buffer && stored.buffer.byteLength > 0);
    log.push(`download ok=${okDownload} bytes=${stored?.buffer?.byteLength ?? 0}`);
    if (!okDownload) {
      failedStage = failedStage ?? "download";
      failureReason = failureReason ?? "download_empty";
    }

    if (options.otherUserId && artifactId) {
      const leak = await getStoredDeliverableForUser(
        artifactId,
        options.otherUserId
      );
      crossUserLeak = Boolean(leak?.buffer && leak.buffer.byteLength > 0);
      log.push(`cross_user_leak=${crossUserLeak}`);
      if (crossUserLeak) {
        failedStage = failedStage ?? "permission";
        failureReason = failureReason ?? "cross_user_access";
      }
    }

    if (options.runRevision !== false && okDownload && okStructure) {
      revisionAttempted = true;
      try {
        const { content: revisedContent, changeSummary } = buildRevisionContent(
          c,
          requestId,
          options.revisionIndex ?? 0
        );
        const revisedFile = await generateForCase({
          ...c,
          content: revisedContent,
          title: `${c.title}_rev`,
        });
        // Re-validate revision bytes before save
        const revStructure = await validateStructure(c.format, revisedFile);
        if (!revStructure.ok || revisedFile.buffer.byteLength === 0) {
          throw new Error(
            `revision_structure_failed:${revStructure.checks
              .filter((x) => !x.ok)
              .map((x) => x.name)
              .join(",")}`
          );
        }
        const rev = await createArtifactRevision({
          sourceArtifactId: artifactId!,
          userId: options.userId,
          buffer: revisedFile.buffer,
          changeReason: "耐久試験再編集",
          changeSummary: `${changeSummary} (${c.caseId})`,
          jobId,
        });
        const sourceStill =
          (await getStoredDeliverableForUser(artifactId!, options.userId))
            ?.buffer?.byteLength ?? 0;
        okRevision =
          Boolean(rev.ok && rev.artifact?.id) &&
          rev.artifact!.id !== artifactId &&
          sourceStill > 0;
        log.push(
          `revision ok=${okRevision} newId=${rev.artifact?.id ?? "null"} sourceBytes=${sourceStill}`
        );
        if (sourceStill <= 0) {
          failedStage = failedStage ?? "revision";
          failureReason = failureReason ?? "source_artifact_lost";
        } else if (!okRevision) {
          failedStage = failedStage ?? "revision";
          failureReason = failureReason ?? "revision_failed";
        }
      } catch (error) {
        failedStage = failedStage ?? "revision";
        failureReason =
          failureReason ??
          (error instanceof Error ? error.message : String(error));
        log.push(`revision error: ${failureReason}`);
      }
    }

    const okFinal =
      okGenerate &&
      okStructure &&
      okStorage &&
      okDb &&
      okPreview &&
      okDownload &&
      !crossUserLeak;

    finalStatus = okFinal ? "completed" : "partial_failed";
    if (!okFinal && !failedStage) failedStage = "final_gate";
  } catch (error) {
    developerCode = "case_error";
    failureReason =
      failureReason ??
      (error instanceof Error ? error.message : String(error));
    failedStage = failedStage ?? "generate";
    log.push(`ERROR ${failureReason}`);
    finalStatus = "failed";
  }

  const okFinal =
    okGenerate &&
    okStructure &&
    okStorage &&
    okDb &&
    okPreview &&
    okDownload &&
    !crossUserLeak;

  const failureClass = okFinal
    ? null
    : classifyArtifactFailure({
        stage: failedStage,
        message: failureReason,
        structureOk: okStructure,
        zeroByte: fileSize === 0,
      });

  const result: ArtifactCaseResult = {
    caseId: c.caseId,
    format: c.format,
    category: c.category,
    okGenerate,
    okStructure,
    okStorage,
    okDb,
    okPreview,
    okDownload,
    okRevision,
    revisionAttempted,
    okFinal,
    requestId,
    jobId,
    artifactId,
    diagnosticId: null,
    startedAt,
    finishedAt: new Date().toISOString(),
    totalMs: Date.now() - startedMs,
    generateMs,
    saveMs,
    previewMs,
    downloadOk: okDownload,
    revisionOk: okRevision,
    retryCount,
    finalStatus,
    failedStage,
    userCode: null,
    developerCode,
    fileSize,
    sha256,
    structureChecks,
    failureClass,
    failureReason,
    environment: options.environment ?? "local",
    log,
    screenshotPath: null,
    evidencePath: null,
  };

  const caseDir = join(options.outDir, "cases", c.caseId);
  mkdirSync(caseDir, { recursive: true });
  const evidencePath = join(caseDir, "result.json");
  writeFileSync(evidencePath, JSON.stringify(result, null, 2), "utf8");
  writeFileSync(join(caseDir, "log.txt"), log.join("\n"), "utf8");
  result.evidencePath = evidencePath;
  return result;
}
