export {
  CEO_APPROVAL_EXCELLENCE,
  CONSULTING_QUALITY_BAR,
  DELIVERABLE_FORMAT_GUIDANCE,
  PLANNER_EXCELLENCE,
  QA_EXCELLENCE,
  RESEARCH_EXCELLENCE,
  REVIEWER_EXCELLENCE,
  WORKER_EXCELLENCE,
} from "./output-standards";
