import type { MihonShowcaseCompany } from "./types";

/** Curated 見本 — what ATLAS can build, not demo data. */
export const MIHON_SHOWCASE_COMPANIES: readonly MihonShowcaseCompany[] = [
  {
    id: "blogging",
    icon: "📝",
    name: "ブログ運営",
    recommendation: "初めての方におすすめ",
    description: "SEO記事の作成から投稿、改善まで自動で行います。",
    capabilities: [
      "記事作成",
      "キーワード調査",
      "WordPress投稿",
      "アクセス分析",
      "改善提案",
    ],
    templateId: "blogging",
    kind: "company",
  },
  {
    id: "youtube",
    icon: "🎥",
    name: "YouTube制作",
    recommendation: "人気",
    description: "企画から台本、概要欄まで自動で作成します。",
    capabilities: [
      "企画",
      "台本",
      "タイトル作成",
      "概要欄",
      "サムネイル案",
    ],
    templateId: "youtube",
    kind: "company",
  },
  {
    id: "sales",
    icon: "💼",
    name: "営業支援",
    recommendation: "営業向け",
    description: "営業活動を専属AI秘書が支援します。",
    capabilities: [
      "営業資料",
      "提案書",
      "営業メール",
      "顧客整理",
      "商談準備",
    ],
    templateId: "sales",
    kind: "company",
  },
  {
    id: "ecommerce",
    icon: "🛍",
    name: "EC運営",
    recommendation: "EC向け",
    description: "ネットショップ運営を支援します。",
    capabilities: [
      "商品説明",
      "広告文",
      "売上分析",
      "改善提案",
      "SNS投稿",
    ],
    templateId: "ecommerce",
    kind: "company",
  },
  {
    id: "marketing-agency",
    icon: "📈",
    name: "マーケティング支援",
    recommendation: "マーケティング向け",
    description: "市場調査から戦略立案まで支援します。",
    capabilities: [
      "市場調査",
      "競合分析",
      "広告戦略",
      "SNS分析",
      "レポート作成",
    ],
    templateId: "marketing-agency",
    kind: "company",
  },
  {
    id: "sns",
    icon: "📱",
    name: "SNS運営",
    recommendation: "SNS運営向け",
    description: "SNSの投稿から分析まで自動化します。",
    capabilities: [
      "投稿作成",
      "画像作成",
      "予約投稿",
      "分析",
      "改善提案",
    ],
    templateId: "affiliate",
    kind: "company",
  },
  {
    id: "knowledge",
    icon: "🧠",
    name: "ナレッジ管理",
    recommendation: "すぐ始められます",
    description: "社内情報を整理し、AIが活用できるようにします。",
    capabilities: ["情報整理", "検索", "FAQ", "共有", "自動学習"],
    templateId: "saas",
    kind: "company",
  },
  {
    id: "original",
    icon: "✨",
    name: "オリジナル会社",
    description: "自分だけの業務テンプレートを一から作ります。",
    capabilities: [],
    kind: "original",
  },
] as const;
