/** Japanese presentation copy helpers. Never inject leftover English chrome. */

const FORBIDDEN_TITLES =
  /^(key points|overview|summary|agenda|thank you|contents)$/i;

export const PPT_LABEL = {
  agenda: "本日の流れ",
  summary: "まとめ",
  summaryCont: "まとめ（続き）",
  next: "次の一歩",
  cta: "ご相談ください",
} as const;

export function isForbiddenEnglishTitle(title: string): boolean {
  return FORBIDDEN_TITLES.test(title.trim());
}

export function sanitizeSlideTitle(title: string): string {
  const cleaned = title
    .replace(/\s*[—–-]\s*Key points(?: \(cont\.\))?$/i, "")
    .replace(/\s*\(cont\.\)$/i, "（続き）")
    .replace(/^Generated by Atlas.*$/i, "")
    .trim();
  if (!cleaned || isForbiddenEnglishTitle(cleaned)) return "要点";
  return shortenTitle(cleaned);
}

export function shortenTitle(title: string, max = 28): string {
  const t = title.replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  return `${t.slice(0, max - 1)}…`;
}

/** Split prose into short bullets. Never shrink font to cram a paragraph. */
export function proseToBullets(text: string, maxItems = 5): string[] {
  const sentences = text
    .split(/(?<=[。．.!?！？])\s+|\n+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0 && s !== " ");
  const bullets: string[] = [];
  for (const sentence of sentences) {
    if (sentence.length <= 42) {
      bullets.push(sentence);
    } else {
      const cut = sentence.slice(0, 40).replace(/[、,]\s*\S*$/, "");
      bullets.push(`${cut}…`);
    }
    if (bullets.length >= maxItems) break;
  }
  return bullets;
}

export function limitBullets(items: string[], max = 5): string[][] {
  const cleaned = items
    .map((item) => item.replace(/\s+/g, " ").trim())
    .filter(Boolean)
    .map((item) => (item.length > 48 ? `${item.slice(0, 46)}…` : item));
  const chunks: string[][] = [];
  for (let i = 0; i < cleaned.length; i += max) {
    chunks.push(cleaned.slice(i, i + max));
  }
  return chunks.length > 0 ? chunks : [[]];
}

export type KpiItem = { label: string; value: string };

const KPI_VALUE =
  /([＋+\-]?\d[\d,.]*(?:\.\d+)?\s*%|¥\s*[\d,]+(?:\s*\/\s*月)?|[\d,]+(?:円|時間|件|社|人))/;
const KPI_PATTERN = new RegExp(`([^。\\n｜|]{0,16}?)${KPI_VALUE.source}`, "g");

export function extractKpis(text: string): KpiItem[] {
  const found: KpiItem[] = [];
  const seen = new Set<string>();
  for (const match of text.matchAll(KPI_PATTERN)) {
    const value = (match[2] ?? "").replace(/\s+/g, "");
    const label = (match[1] ?? "").replace(/[:：]\s*$/, "").trim() || "指標";
    const key = `${label}:${value}`;
    if (seen.has(key)) continue;
    seen.add(key);
    found.push({ label: shortenTitle(label, 12), value });
    if (found.length >= 4) break;
  }
  return found;
}

/** Prefer a conclusion-bearing title when the first bullet already states the point. */
export function conclusionTitle(sectionTitle: string, bullets: string[]): string {
  const first = (bullets[0] ?? "").replace(/[。．]$/, "");
  if (!first) return sanitizeSlideTitle(sectionTitle);
  const kpi = first.match(KPI_VALUE);
  if (kpi && first.length <= 32) {
    return sanitizeSlideTitle(first);
  }
  if (first.length <= 36 && /増加|減少|削減|改善|不足|必要|決定/.test(first)) {
    return sanitizeSlideTitle(first);
  }
  if (kpi) {
    const cut = first.slice(0, 28).replace(/[、,]\s*\S*$/, "");
    return sanitizeSlideTitle(cut || first.slice(0, 27));
  }
  return sanitizeSlideTitle(sectionTitle);
}
