export type Runbook = {
  id: string;
  title: string;
  detect: string;
  impact: string;
  firstResponse: string[];
  stopTargets: string[];
  investigate: string[];
  logSearch: string[];
  recover: string[];
  prevent: string[];
  userMessage: string;
  escalate: string;
  doneWhen: string;
};

export const RELEASE_GATE_RUNBOOKS: Runbook[] = [
  {
    id: "openai_outage",
    title: "OpenAI障害",
    detect: "OpenAI error/429/timeout 急増、AI 成功率急落",
    impact: "成果物生成・Vision・OCR・要約が失敗",
    firstResponse: [
      "Kill Switch: vision / new_jobs を検討",
      "Capability: vision / ocr / 生成系を一時停止",
      "Status Page を「調査中」へ",
    ],
    stopTargets: ["vision", "ocr", "word/excel/pdf/pptx 生成", "automation"],
    investigate: ["provider status", "api_error_rate", "timeout率", "request_id サンプル"],
    logSearch: ["ops_events type=ai_error", "OpenAI response status", "request_id"],
    recover: ["provider 復旧確認後、canary で 1 機能だけ再開", "成功率監視"],
    prevent: ["エコモード優先", "リトライ上限", "フォールバック文言"],
    userMessage: "ただいま AI 処理が不安定です。しばらくお待ちください。",
    escalate: "オーナー + on-call",
    doneWhen: "エラー率通常レンジ + Status 復旧済み",
  },
  {
    id: "vision_timeout",
    title: "Vision timeout急増",
    detect: "Vision p95/timeout 閾値超え",
    impact: "画像解析・画像→成果物",
    firstResponse: ["Kill: vision", "Capability: vision/image_* off", "Status 更新"],
    stopTargets: ["vision", "image_to_*"],
    investigate: ["画像サイズ分布", "モデル", "キュー滞留"],
    logSearch: ["vision evidence", "timeout", "request_id"],
    recover: ["縮小画像パス確認後、段階再開"],
    prevent: ["サイズ上限", "タイムアウト明示", "再解析導線"],
    userMessage: "画像の解析が混み合っています。後でもう一度お試しください。",
    escalate: "オーナー",
    doneWhen: "timeout率低下 + 再試験 PASS",
  },
  {
    id: "db_outage",
    title: "DB障害",
    detect: "connection error / query timeout 急増",
    impact: "ログイン後ほぼ全機能",
    firstResponse: ["新規ジョブ停止", "書き込み系停止検討", "Status 重大障害"],
    stopTargets: ["new_jobs", "billing checkout", "外部送信"],
    investigate: ["接続数", "ロック", "migration 直後か"],
    logSearch: ["postgres errors", "supabase status"],
    recover: ["フェイルオーバー / 復旧後 health", "整合 jobs"],
    prevent: ["接続プール監視", "migration dry-run"],
    userMessage: "システムメンテナンス中です。データの保全を優先しています。",
    escalate: "インフラ + オーナー",
    doneWhen: "health OK + smoke PASS",
  },
  {
    id: "storage_outage",
    title: "Storage障害",
    detect: "upload/download/signed URL 失敗率上昇",
    impact: "成果物DL・プレビュー・アップロード",
    firstResponse: ["大容量アップロード停止", "Status 更新"],
    stopTargets: ["large_upload", "必要なら new_jobs"],
    investigate: ["bucket ACL", "quota", "region"],
    logSearch: ["storage permission denied", "orphan"],
    recover: ["ACL 修正後 smoke download"],
    prevent: ["容量アラート", "orphan 掃除"],
    userMessage: "ファイルの保存・取得が不安定です。",
    escalate: "オーナー",
    doneWhen: "upload/download 成功率復帰",
  },
  {
    id: "queue_stopped",
    title: "Queue停止",
    detect: "queue length 増加・処理 0",
    impact: "非同期ジョブ遅延",
    firstResponse: ["new_jobs 停止", "worker 確認"],
    stopTargets: ["new_jobs", "automation"],
    investigate: ["tick cron", "worker health", "stuck"],
    logSearch: ["jobs status=queued", "tick logs"],
    recover: ["worker 再起動", "stuck 解放"],
    prevent: ["stuck アラート", "heartbeat"],
    userMessage: "処理が遅延しています。完了次第お知らせします。",
    escalate: "オーナー",
    doneWhen: "queue 消化 + stuck 0",
  },
  {
    id: "worker_stopped",
    title: "Worker停止",
    detect: "worker health fail / 処理停止",
    impact: "ジョブ完了しない",
    firstResponse: ["new_jobs 停止", "実行中ジョブ方針を Status に明記"],
    stopTargets: ["new_jobs", "automation"],
    investigate: ["デプロイ", "OOM", "cron"],
    logSearch: ["worker", "tick", "memory"],
    recover: ["再デプロイ / スケール", "再試行"],
    prevent: ["health check", "メモリ監視"],
    userMessage: "バックグラウンド処理を復旧しています。",
    escalate: "オーナー",
    doneWhen: "worker healthy + ジョブ進行",
  },
  {
    id: "notify_outage",
    title: "通知障害",
    detect: "Push/メール成功率低下",
    impact: "完了通知漏れ",
    firstResponse: ["push / email_outbound 停止検討", "UI 完了表示を頼る案内"],
    stopTargets: ["push", "email_outbound"],
    investigate: ["VAPID", "provider", "誤通知"],
    logSearch: ["notification", "pushRate"],
    recover: ["再送ポリシー確認後再開"],
    prevent: ["二重送信防止キー"],
    userMessage: "完了通知が遅れる場合があります。ホームの一覧をご確認ください。",
    escalate: "オーナー",
    doneWhen: "通知成功率復帰",
  },
  {
    id: "x_outage",
    title: "X投稿障害",
    detect: "X 成功率低下 / 重複投稿",
    impact: "外部投稿",
    firstResponse: ["Kill: x_post", "Capability: x_post off"],
    stopTargets: ["x_post", "必要なら all_external"],
    investigate: ["token", "重複 externalActionId", "rate limit"],
    logSearch: ["external_actions provider=x"],
    recover: ["重複確認後、手動再投稿はユーザー確認必須"],
    prevent: ["idempotency key", "確認 UI"],
    userMessage: "X への投稿を一時停止しています。",
    escalate: "オーナー",
    doneWhen: "重複なし + 成功率復帰",
  },
  {
    id: "gmail_outage",
    title: "Gmail障害",
    detect: "Gmail API 失敗 / 誤送信疑い",
    impact: "メール送信",
    firstResponse: ["Kill: email_outbound / gmail_send", "誤送信なら即調査"],
    stopTargets: ["gmail_send", "email_outbound"],
    investigate: ["送信先", "request_id", "下書きか送信か"],
    logSearch: ["gmail", "external_actions"],
    recover: ["ユーザーへ事実連絡", "再接続導線"],
    prevent: ["送信前確認", "下書き既定"],
    userMessage: "メール送信を一時停止しています。",
    escalate: "オーナー + 必要なら法務",
    doneWhen: "停止解除条件クリア + 再発防止",
  },
  {
    id: "calendar_outage",
    title: "Calendar障害",
    detect: "Calendar API 失敗",
    impact: "予定登録",
    firstResponse: ["Kill: calendar_write"],
    stopTargets: ["calendar_write"],
    investigate: ["scope", "token refresh"],
    logSearch: ["calendar", "token refresh"],
    recover: ["再接続後 canary"],
    prevent: ["refresh 失敗アラート"],
    userMessage: "カレンダー連携を一時停止しています。",
    escalate: "オーナー",
    doneWhen: "成功率復帰",
  },
  {
    id: "wordpress_outage",
    title: "WordPress障害",
    detect: "WP 投稿失敗 / 誤公開",
    impact: "公開投稿",
    firstResponse: ["Kill: wordpress_publish", "誤公開なら非公開化"],
    stopTargets: ["wordpress_publish"],
    investigate: ["投稿 URL", "権限"],
    logSearch: ["wordpress", "external_actions"],
    recover: ["下書きのみ再開から"],
    prevent: ["公開前確認", "下書き既定"],
    userMessage: "WordPress 公開を一時停止しています。",
    escalate: "オーナー",
    doneWhen: "誤公開なし + 成功率",
  },
  {
    id: "dropbox_outage",
    title: "Dropbox障害",
    detect: "書き込み失敗",
    impact: "外部保存",
    firstResponse: ["Kill: dropbox_write"],
    stopTargets: ["dropbox_write"],
    investigate: ["token", "quota"],
    logSearch: ["dropbox"],
    recover: ["再接続"],
    prevent: ["書き込み前容量チェック"],
    userMessage: "Dropbox 保存を一時停止しています。",
    escalate: "オーナー",
    doneWhen: "成功率復帰",
  },
  {
    id: "stripe_outage",
    title: "Stripe障害",
    detect: "Checkout/Webhook 失敗",
    impact: "課金・無料体験移行",
    firstResponse: ["Kill: billing", "Capability: billing/trial off"],
    stopTargets: ["billing", "signup 検討"],
    investigate: ["Stripe status", "webhook 署名", "二重 claim"],
    logSearch: ["stripe", "billing_events", "webhook"],
    recover: ["手動 reconcile", "顧客へ案内"],
    prevent: ["idempotent claim", "plan drift 監視"],
    userMessage: "お支払い処理を一時停止しています。重複課金は発生しないよう停止しています。",
    escalate: "オーナー + 経理",
    doneWhen: "Webhook 正常 + plan 整合",
  },
  {
    id: "webhook_outage",
    title: "Webhook障害",
    detect: "署名失敗・遅延・順序入れ替わり",
    impact: "plan/quota 不整合",
    firstResponse: ["billing 停止", "手動付与は監査付きのみ"],
    stopTargets: ["billing"],
    investigate: ["event id 重複", "順序", "署名鍵"],
    logSearch: ["stripe-webhook", "billing_events"],
    recover: ["replay 安全確認後処理", "reconcile"],
    prevent: ["冪等キー必須"],
    userMessage: "ご契約状態の反映が遅れる場合があります。",
    escalate: "オーナー",
    doneWhen: "未処理 0 + 整合",
  },
  {
    id: "auth_outage",
    title: "認証障害",
    detect: "Clerk/セッション失敗急増",
    impact: "ログイン不可",
    firstResponse: ["Status", "signup 停止検討"],
    stopTargets: ["signup"],
    investigate: ["Clerk status", "JWT", "clock skew"],
    logSearch: ["auth", "401/403"],
    recover: ["プロバイダ復旧後 smoke login"],
    prevent: ["認証エラー率アラート"],
    userMessage: "ログインに問題が発生しています。",
    escalate: "オーナー",
    doneWhen: "ログイン smoke PASS",
  },
  {
    id: "data_leak_suspected",
    title: "データ漏洩疑い",
    detect: "他ユーザー成果物閲覧 / 権限漏れテスト失敗 / 異常アクセス",
    impact: "重大 — Critical",
    firstResponse: [
      "全外部送信停止 (all_external)",
      "必要なら新規ジョブ停止",
      "該当ユーザー隔離",
      "法務・オーナー即時",
    ],
    stopTargets: ["all_external", "new_jobs", "signup"],
    investigate: ["request_id", "userId 境界", "監査ログ", "アクセス範囲"],
    logSearch: ["authz", "artifact access", "audit"],
    recover: ["パッチ後全権テスト再実行", "影響ユーザー通知（専門家確認）"],
    prevent: ["tenant isolation 回帰テスト必須"],
    userMessage: "セキュリティ上の確認のため一部機能を停止しています。",
    escalate: "オーナー + 専門家（法務）必須",
    doneWhen: "原因除去 + 権限テスト Critical 0 + 専門家確認",
  },
  {
    id: "mis_send",
    title: "誤送信",
    detect: "誤った宛先へのメール/投稿報告",
    impact: "信頼・法務リスク",
    firstResponse: ["対象チャネル Kill", "送信ログ保全", "ユーザー連絡"],
    stopTargets: ["email_outbound", "x_post", "wordpress_publish"],
    investigate: ["宛先決定ロジック", "確認 UI スキップ有無"],
    logSearch: ["externalActionId", "request_id"],
    recover: ["可能なら撤回/削除", "再発防止デプロイ"],
    prevent: ["送信前確認必須", "下書き既定"],
    userMessage: "該当の送信機能を停止し調査しています。",
    escalate: "オーナー + 必要なら法務",
    doneWhen: "停止解除前に確認フロー検証完了",
  },
  {
    id: "duplicate_post",
    title: "重複投稿",
    detect: "同一内容の二重外部投稿",
    impact: "ブランド・迷惑行為",
    firstResponse: ["対象連携 Kill", "idempotency 確認"],
    stopTargets: ["x_post", "wordpress_publish", "all_external"],
    investigate: ["externalActionId", "retry 経路"],
    logSearch: ["duplicate", "idempotency"],
    recover: ["重複削除案内", "キー修正"],
    prevent: ["冪等キー必須 + テスト"],
    userMessage: "重複投稿を防ぐため連携を一時停止しています。",
    escalate: "オーナー",
    doneWhen: "再現テストで重複 0",
  },
  {
    id: "duplicate_charge",
    title: "重複課金",
    detect: "二重 Checkout / Webhook 二重処理",
    impact: "金銭事故 — Critical",
    firstResponse: ["Kill: billing", "Stripe ダッシュボード確認", "返金方針（専門家）"],
    stopTargets: ["billing", "trial"],
    investigate: ["session id", "claim", "customer"],
    logSearch: ["billing_events", "stripe"],
    recover: ["返金/調整（専門家確認）", "plan 整合"],
    prevent: ["idempotent claim 回帰"],
    userMessage: "課金処理を停止し、重複がないか確認しています。",
    escalate: "オーナー + 経理/専門家",
    doneWhen: "顧客残高正しい + 再発防止マージ",
  },
  {
    id: "artifact_corrupt",
    title: "成果物破損",
    detect: "0バイト・開けない・プレビュー失敗",
    impact: "信頼・サポート負荷",
    firstResponse: ["該当形式 Capability 停止", "サンプル保全"],
    stopTargets: ["word/excel/pdf/pptx 該当"],
    investigate: ["生成ログ", "storage", "revision"],
    logSearch: ["artifactId", "request_id", "corrupt"],
    recover: ["再生成導線", "必要なら復元試験"],
    prevent: ["生成後バリデーション"],
    userMessage: "該当のファイル形式を一時停止し修正しています。",
    escalate: "オーナー",
    doneWhen: "耐久試験再 PASS",
  },
  {
    id: "deploy_fail",
    title: "本番デプロイ失敗",
    detect: "deploy error / health fail",
    impact: "一部ユーザーに旧/新混在",
    firstResponse: ["ロールバック判定", "canary 停止"],
    stopTargets: ["必要なら new_jobs"],
    investigate: ["build log", "migration"],
    logSearch: ["deploy", "health"],
    recover: ["rollback 手順実行", "smoke"],
    prevent: ["pre-deploy check 必須化"],
    userMessage: "更新作業の影響を確認しています。",
    escalate: "オーナー",
    doneWhen: "health + smoke PASS",
  },
  {
    id: "rollback_fail",
    title: "rollback失敗",
    detect: "rollback 後も異常 / migration 非互換",
    impact: "長期障害",
    firstResponse: ["読み取り優先モード検討", "Status 重大", "バックアップからの復元検討"],
    stopTargets: ["new_jobs", "billing", "all_external"],
    investigate: ["DB schema 互換", "アプリ版"],
    logSearch: ["migration", "rollback"],
    recover: ["forward-fix または DB 復元（RPO 内）"],
    prevent: ["expand/contract migration", "rollback 試験"],
    userMessage: "復旧作業を優先しています。データの保全を最優先にしています。",
    escalate: "オーナー + インフラ",
    doneWhen: "サービス利用可能 + データ整合",
  },
];
