/**
 * Employee system prompts — grouped by department.
 *
 * Each file exports named constants consumed by `lib/employees/employees/*.ts`.
 * Prompt text must not be duplicated elsewhere.
 */

export {
  ATLAS_CEO_SYSTEM_PROMPT,
  CEO_OFFICE_DEPARTMENT_SYSTEM_PROMPT,
  EXECUTIVE_ASSISTANT_SYSTEM_PROMPT,
} from "./ceo-office";

export {
  LEAD_PLANNER_SYSTEM_PROMPT,
  PLANNING_DEPARTMENT_SYSTEM_PROMPT,
  PROJECT_COORDINATOR_SYSTEM_PROMPT,
} from "./planning";

export {
  DEVELOPMENT_DEPARTMENT_SYSTEM_PROMPT,
  SENIOR_DEVELOPER_SYSTEM_PROMPT,
  FULL_STACK_ENGINEER_SYSTEM_PROMPT,
} from "./development";

export {
  QUALITY_ASSURANCE_DEPARTMENT_SYSTEM_PROMPT,
  QUALITY_LEAD_SYSTEM_PROMPT,
  QA_SPECIALIST_SYSTEM_PROMPT,
} from "./quality-assurance";

export {
  SALES_DEPARTMENT_SYSTEM_PROMPT,
  SALES_DIRECTOR_SYSTEM_PROMPT,
  ACCOUNT_EXECUTIVE_SYSTEM_PROMPT,
} from "./sales";

export {
  RESEARCH_DEPARTMENT_SYSTEM_PROMPT,
  RESEARCH_LEAD_SYSTEM_PROMPT,
  DATA_ANALYST_SYSTEM_PROMPT,
} from "./research";

export {
  DESIGN_DEPARTMENT_SYSTEM_PROMPT,
  CREATIVE_DIRECTOR_SYSTEM_PROMPT,
  UI_DESIGNER_SYSTEM_PROMPT,
} from "./design";

export {
  MARKETING_DEPARTMENT_SYSTEM_PROMPT,
  MARKETING_DIRECTOR_SYSTEM_PROMPT,
  CONTENT_STRATEGIST_SYSTEM_PROMPT,
} from "./marketing";

export {
  LEGAL_DEPARTMENT_SYSTEM_PROMPT,
  GENERAL_COUNSEL_SYSTEM_PROMPT,
  COMPLIANCE_OFFICER_SYSTEM_PROMPT,
} from "./legal";

export {
  FINANCE_DEPARTMENT_SYSTEM_PROMPT,
  FINANCE_DIRECTOR_SYSTEM_PROMPT,
  FINANCIAL_ANALYST_SYSTEM_PROMPT,
} from "./finance";

export {
  HR_DEPARTMENT_SYSTEM_PROMPT,
  HR_DIRECTOR_SYSTEM_PROMPT,
  TALENT_PARTNER_SYSTEM_PROMPT,
} from "./hr";

export {
  CUSTOMER_SUCCESS_DEPARTMENT_SYSTEM_PROMPT,
  CS_DIRECTOR_SYSTEM_PROMPT,
  SUPPORT_LEAD_SYSTEM_PROMPT,
} from "./customer-success";
