/**
 * Automation V2 Capability ↔ existing MINERVOT implementation matrix.
 * Source of truth for Phase 8 Live Execution wiring (no engine duplication).
 */

export type CapabilityMatrixRow = {
  stepType: string;
  existingImplementation: string;
  existingApiOrService: string;
  connectedFromAutomationV2: boolean;
  authRequirement: string;
  inputSchema: string;
  outputSchema: string;
  idempotency: string;
  retryable: boolean;
  timeoutMs: number;
  successCondition: string;
  failureCondition: string;
  audit: string;
  productionReady: boolean;
  notes?: string;
};

export const AUTOMATION_V2_CAPABILITY_MATRIX: readonly CapabilityMatrixRow[] = [
  {
    stepType: "word_generate",
    existingImplementation: "lib/deliverables",
    existingApiOrService: "generateDeliverables({ formats: ['docx'] })",
    connectedFromAutomationV2: true,
    authRequirement: "user session + storage credentials",
    inputSchema: "content|instruction|freeformNotes, title?",
    outputSchema: "artifactIds, downloadUrl, mimeType, sizeBytes",
    idempotency: "artifact key runId+stepId+attempt+format (durable)",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "real file size>0, not placeholder, storage+DB registered",
    failureCondition: "empty content, placeholder, storage failure",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "excel_generate",
    existingImplementation: "lib/deliverables",
    existingApiOrService: "generateDeliverables({ formats: ['xlsx'] })",
    connectedFromAutomationV2: true,
    authRequirement: "user session + storage credentials",
    inputSchema: "content|instruction|freeformNotes, title?",
    outputSchema: "artifactIds, downloadUrl",
    idempotency: "artifact key durable",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "real xlsx stored",
    failureCondition: "generation/storage failure",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "pdf_generate",
    existingImplementation: "lib/deliverables",
    existingApiOrService: "generateDeliverables({ formats: ['pdf'] })",
    connectedFromAutomationV2: true,
    authRequirement: "user session + storage credentials",
    inputSchema: "content|instruction|freeformNotes",
    outputSchema: "artifactIds, downloadUrl",
    idempotency: "artifact key durable",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "real pdf stored",
    failureCondition: "generation/storage failure",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "powerpoint_generate",
    existingImplementation: "lib/deliverables",
    existingApiOrService: "generateDeliverables({ formats: ['pptx'] })",
    connectedFromAutomationV2: true,
    authRequirement: "user session + storage credentials",
    inputSchema: "content|instruction|freeformNotes",
    outputSchema: "artifactIds, downloadUrl",
    idempotency: "artifact key durable",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "real pptx stored",
    failureCondition: "generation/storage failure",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "file_convert",
    existingImplementation: "lib/deliverables + prior artifact",
    existingApiOrService: "generateDeliverables with source content",
    connectedFromAutomationV2: true,
    authRequirement: "user session + storage",
    inputSchema: "priorArtifacts deliverable + targetFormat",
    outputSchema: "converted artifactIds",
    idempotency: "artifact key durable",
    retryable: true,
    timeoutMs: 180_000,
    successCondition: "converted file stored",
    failureCondition: "missing prior artifact / convert fail",
    audit: "step_executed durable",
    productionReady: true,
    notes: "Word/Excel/PPT→PDF via regenerate path",
  },
  {
    stepType: "vision_analysis / ocr / data_extract",
    existingImplementation: "lib/vision",
    existingApiOrService: "analyzeUserImageBatch",
    connectedFromAutomationV2: true,
    authRequirement: "OPENAI_API_KEY + attachmentId",
    inputSchema: "attachmentId",
    outputSchema: "analysis text bindings",
    idempotency: "step attempt key",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "OpenAI vision result returned",
    failureCondition: "missing key / attachment / API error → needs_configuration",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "x_post",
    existingImplementation: "lib/integrations/x/post",
    existingApiOrService: "postTweetNowForUser",
    connectedFromAutomationV2: true,
    authRequirement: "X OAuth connected + scopes",
    inputSchema: "text (+ optional media)",
    outputSchema: "tweetId externalActionId",
    idempotency: "external action key automation+occurrence+step",
    retryable: true,
    timeoutMs: 60_000,
    successCondition: "real tweetId from X API",
    failureCondition: "not connected / revoked / 429 / 5xx",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "gmail",
    existingImplementation: "lib/integrations/google/gmail",
    existingApiOrService:
      "createGmailComposeDraftForUser / saveGmailDraftForUser / sendReplyForUser",
    connectedFromAutomationV2: true,
    authRequirement: "Google OAuth gmail scopes",
    inputSchema: "to, subject?, body?, mode=draft|send, messageId? for reply/send",
    outputSchema: "draftId | messageId",
    idempotency: "external action key",
    retryable: true,
    timeoutMs: 60_000,
    successCondition: "Gmail API draftId/messageId returned",
    failureCondition: "not connected / invalid recipient / API error",
    audit: "step_executed durable",
    productionReady: true,
    notes: "send requires approval + messageId (reply send)",
  },
  {
    stepType: "google_calendar",
    existingImplementation: "lib/integrations/google/calendar",
    existingApiOrService: "createCalendarEventForUser",
    connectedFromAutomationV2: true,
    authRequirement: "Google OAuth calendar scopes",
    inputSchema: "title, startAt?, endAt?, attendees?",
    outputSchema: "eventId",
    idempotency: "external action key",
    retryable: true,
    timeoutMs: 60_000,
    successCondition: "eventId from Google Calendar API",
    failureCondition: "not connected / API error",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "wordpress",
    existingImplementation: "lib/integrations/wordpress/post",
    existingApiOrService: "createWordPressPostForUser",
    connectedFromAutomationV2: true,
    authRequirement: "WordPress site credentials",
    inputSchema: "title, content, status=draft|publish",
    outputSchema: "postId, link",
    idempotency: "external action key",
    retryable: true,
    timeoutMs: 90_000,
    successCondition: "postId returned",
    failureCondition: "not connected / API error; publish needs approval",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "dropbox",
    existingImplementation: "lib/integrations/dropbox",
    existingApiOrService: "uploadDropboxFileForUser",
    connectedFromAutomationV2: true,
    authRequirement: "Dropbox OAuth",
    inputSchema: "saveTarget + prior deliverable artifact",
    outputSchema: "path, fileId",
    idempotency: "external action key",
    retryable: true,
    timeoutMs: 120_000,
    successCondition: "Dropbox file id/path from API",
    failureCondition: "missing prior file / not connected / upload fail",
    audit: "step_executed durable",
    productionReady: true,
  },
  {
    stepType: "notify",
    existingImplementation: "lib/notifications/service",
    existingApiOrService: "createNotification",
    connectedFromAutomationV2: true,
    authRequirement: "none (in-app)",
    inputSchema: "title?, message?",
    outputSchema: "notificationId",
    idempotency: "notification delivery key",
    retryable: true,
    timeoutMs: 15_000,
    successCondition: "notification row created for user",
    failureCondition: "service error",
    audit: "step_executed durable",
    productionReady: true,
    notes: "Push/email channels not fully wired as live adapters",
  },
  {
    stepType: "orchestrate",
    existingImplementation: "AI employees / planner (core — do not reimplement)",
    existingApiOrService: "n/a",
    connectedFromAutomationV2: false,
    authRequirement: "n/a",
    inputSchema: "n/a",
    outputSchema: "n/a",
    idempotency: "n/a",
    retryable: false,
    timeoutMs: 0,
    successCondition: "never — fail-closed",
    failureCondition: "missing_adapter always",
    audit: "step_executed failure",
    productionReady: false,
    notes: "Intentionally unwired (core pipeline)",
  },
] as const;
