/**
 * Placeholder Supabase Database type.
 * Replace with generated types after running:
 *   npx supabase gen types typescript --project-id <id> > lib/supabase/database.types.ts
 */
export type Database = {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          user_id: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees: unknown;
          result: unknown | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id?: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          work_request?: string;
          status?: string;
          progress?: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_user_state: {
        Row: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          domain?: string;
          payload?: unknown;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_billing_subscriptions: {
        Row: {
          user_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          plan_id: string;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          updated_at: string;
          automations_suspended: boolean | null;
          payment_failure_grace_ends_at: string | null;
          plan_profile_synced_at: string | null;
        };
        Insert: {
          user_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id: string;
          status: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Update: {
          user_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id?: string;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Relationships: [];
      };
      atlas_stripe_webhook_events: {
        Row: {
          event_id: string;
          event_type: string | null;
          status: string;
          claimed_at: string;
          lease_expires_at: string;
          processed_at: string | null;
        };
        Insert: {
          event_id: string;
          event_type?: string | null;
          status?: string;
          claimed_at?: string;
          lease_expires_at?: string;
          processed_at?: string | null;
        };
        Update: {
          event_id?: string;
          event_type?: string | null;
          status?: string;
          claimed_at?: string;
          lease_expires_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      atlas_google_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          account_username: string | null;
          provider_user_id: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_dropbox_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          provider_user_id: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_settings: {
        Row: {
          user_id: string;
          enabled: boolean;
          mode: string;
          purpose: string;
          themes: unknown;
          audience: string;
          tone: string;
          frequency: string;
          days_of_week: unknown;
          post_times: unknown;
          timezone: string;
          include_hashtags: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_runs: {
        Row: {
          id: string;
          user_id: string;
          slot_key: string;
          scheduled_for: string | null;
          status: string;
          mode: string;
          post_type: string | null;
          text: string | null;
          tweet_id: string | null;
          tweet_url: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          slot_key: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          slot_key?: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_image_attachments: {
        Row: {
          id: string;
          user_id: string;
          job_id: string;
          original_file_name: string;
          mime_type: string;
          original_mime_type: string | null;
          original_bytes: number;
          processed_bytes: number;
          width: number;
          height: number;
          content_hash: string;
          original_storage_path: string;
          processed_storage_path: string;
          retention_policy: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          job_id?: string;
          original_file_name: string;
          mime_type: string;
          original_mime_type?: string | null;
          original_bytes: number;
          processed_bytes: number;
          width?: number;
          height?: number;
          content_hash: string;
          original_storage_path: string;
          processed_storage_path: string;
          retention_policy?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          job_id?: string;
          original_file_name?: string;
          mime_type?: string;
          original_mime_type?: string | null;
          original_bytes?: number;
          processed_bytes?: number;
          width?: number;
          height?: number;
          content_hash?: string;
          original_storage_path?: string;
          processed_storage_path?: string;
          retention_policy?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform: string | null;
          browser: string | null;
          device_name: string | null;
          user_agent: string | null;
          failure_count: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          user_agent?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth_key?: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          user_agent?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Relationships: [];
      };
      atlas_deliverable_files: {
        Row: {
          id: string;
          user_id: string;
          file_name: string;
          format: string;
          mime_type: string;
          is_placeholder: boolean;
          source_content: string;
          base_file_name: string;
          size_bytes: number | null;
          content_base64: string | null;
          generated_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          file_name: string;
          format: string;
          mime_type: string;
          is_placeholder?: boolean;
          source_content: string;
          base_file_name: string;
          size_bytes?: number | null;
          content_base64?: string | null;
          generated_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_name?: string;
          format?: string;
          mime_type?: string;
          is_placeholder?: boolean;
          source_content?: string;
          base_file_name?: string;
          size_bytes?: number | null;
          content_base64?: string | null;
          generated_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_reliability_events: {
        Row: {
          id: string;
          metric_key: string | null;
          outcome: string | null;
          duration_ms: number | null;
          job_id: string | null;
          diagnostic_id: string | null;
          user_id: string | null;
          stage: string | null;
          severity: string | null;
          error_code: string | null;
          message: string | null;
          error_message: string | null;
          metadata: unknown;
          created_at: string;
        };
        Insert: {
          id?: string;
          metric_key?: string | null;
          outcome?: string | null;
          duration_ms?: number | null;
          job_id?: string | null;
          diagnostic_id?: string | null;
          user_id?: string | null;
          stage?: string | null;
          severity?: string | null;
          error_code?: string | null;
          message?: string | null;
          error_message?: string | null;
          metadata?: unknown;
          created_at?: string;
        };
        Update: {
          id?: string;
          metric_key?: string | null;
          outcome?: string | null;
          duration_ms?: number | null;
          job_id?: string | null;
          diagnostic_id?: string | null;
          user_id?: string | null;
          stage?: string | null;
          severity?: string | null;
          error_code?: string | null;
          message?: string | null;
          error_message?: string | null;
          metadata?: unknown;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_notification_dlq: {
        Row: {
          id: string;
          notification_id: string;
          user_id: string;
          channel: string;
          title: string;
          message: string;
          attempt_count: number;
          last_error: string | null;
          payload: unknown;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          notification_id: string;
          user_id: string;
          channel: string;
          title: string;
          message: string;
          attempt_count?: number;
          last_error?: string | null;
          payload?: unknown;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          notification_id?: string;
          user_id?: string;
          channel?: string;
          title?: string;
          message?: string;
          attempt_count?: number;
          last_error?: string | null;
          payload?: unknown;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automations: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string;
          status: string;
          trigger: unknown;
          workflow: unknown;
          execution_policy: unknown;
          notification_policy: unknown;
          instruction: unknown;
          memory_policy: unknown;
          legacy_automation_id: string | null;
          schema_version: number;
          last_run_at: string | null;
          next_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          name: string;
          description?: string;
          status: string;
          trigger: unknown;
          workflow: unknown;
          execution_policy: unknown;
          notification_policy: unknown;
          instruction: unknown;
          memory_policy: unknown;
          legacy_automation_id?: string | null;
          schema_version?: number;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string;
          status?: string;
          trigger?: unknown;
          workflow?: unknown;
          execution_policy?: unknown;
          notification_policy?: unknown;
          instruction?: unknown;
          memory_policy?: unknown;
          legacy_automation_id?: string | null;
          schema_version?: number;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automation_runs: {
        Row: {
          id: string;
          automation_id: string;
          user_id: string;
          status: string;
          run_key: string;
          idempotency_key: string;
          schedule_occurrence_key: string | null;
          trigger_type: string;
          scheduled_for: string | null;
          queued_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          attempt_count: number;
          max_attempts: number;
          last_error_code: string | null;
          last_error_message: string | null;
          resolved_instruction: unknown | null;
          memory_references: unknown;
          status_history: unknown;
          approval_expires_at: string | null;
          result_summary: string | null;
          next_retry_at: string | null;
          payload: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          automation_id: string;
          user_id: string;
          status: string;
          run_key: string;
          idempotency_key: string;
          schedule_occurrence_key?: string | null;
          trigger_type: string;
          scheduled_for?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          resolved_instruction?: unknown | null;
          memory_references?: unknown;
          status_history?: unknown;
          approval_expires_at?: string | null;
          result_summary?: string | null;
          next_retry_at?: string | null;
          payload?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          automation_id?: string;
          user_id?: string;
          status?: string;
          run_key?: string;
          idempotency_key?: string;
          schedule_occurrence_key?: string | null;
          trigger_type?: string;
          scheduled_for?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          resolved_instruction?: unknown | null;
          memory_references?: unknown;
          status_history?: unknown;
          approval_expires_at?: string | null;
          result_summary?: string | null;
          next_retry_at?: string | null;
          payload?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automation_jobs: {
        Row: {
          id: string;
          user_id: string;
          automation_id: string | null;
          job_type: string;
          status: string;
          scheduled_at: string | null;
          queued_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          failed_at: string | null;
          current_step: string | null;
          progress_percent: number;
          attempt_count: number;
          max_attempts: number;
          next_retry_at: string | null;
          last_error_code: string | null;
          last_error_message: string | null;
          result_summary: string | null;
          artifact_id: string | null;
          external_result_id: string | null;
          external_result_url: string | null;
          idempotency_key: string;
          push_status: string;
          auto_recovered: boolean;
          steps: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key?: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
