/**
 * Placeholder Supabase Database type.
 * Replace with generated types after running:
 *   npx supabase gen types typescript --project-id <id> > lib/supabase/database.types.ts
 */
export type Database = {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          user_id: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees: unknown;
          result: unknown | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id?: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          work_request?: string;
          status?: string;
          progress?: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_user_state: {
        Row: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          domain?: string;
          payload?: unknown;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_billing_subscriptions: {
        Row: {
          user_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          plan_id: string;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          updated_at: string;
          automations_suspended: boolean | null;
          payment_failure_grace_ends_at: string | null;
          plan_profile_synced_at: string | null;
        };
        Insert: {
          user_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id: string;
          status: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Update: {
          user_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id?: string;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Relationships: [];
      };
      atlas_stripe_webhook_events: {
        Row: {
          event_id: string;
          event_type: string | null;
          processed_at: string;
        };
        Insert: {
          event_id: string;
          event_type?: string | null;
          processed_at?: string;
        };
        Update: {
          event_id?: string;
          event_type?: string | null;
          processed_at?: string;
        };
        Relationships: [];
      };
      atlas_google_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          error_message: string | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          account_username: string | null;
          provider_user_id: string | null;
          error_message: string | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_settings: {
        Row: {
          user_id: string;
          enabled: boolean;
          mode: string;
          purpose: string;
          themes: unknown;
          audience: string;
          tone: string;
          frequency: string;
          days_of_week: unknown;
          post_times: unknown;
          timezone: string;
          include_hashtags: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_runs: {
        Row: {
          id: string;
          user_id: string;
          slot_key: string;
          scheduled_for: string | null;
          status: string;
          mode: string;
          post_type: string | null;
          text: string | null;
          tweet_id: string | null;
          tweet_url: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          slot_key: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          slot_key?: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform: string | null;
          browser: string | null;
          device_name: string | null;
          failure_count: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth_key?: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automation_jobs: {
        Row: {
          id: string;
          user_id: string;
          automation_id: string | null;
          job_type: string;
          status: string;
          scheduled_at: string | null;
          queued_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          failed_at: string | null;
          current_step: string | null;
          progress_percent: number;
          attempt_count: number;
          max_attempts: number;
          next_retry_at: string | null;
          last_error_code: string | null;
          last_error_message: string | null;
          result_summary: string | null;
          artifact_id: string | null;
          external_result_id: string | null;
          external_result_url: string | null;
          idempotency_key: string;
          push_status: string;
          auto_recovered: boolean;
          steps: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key?: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_benchmark_cases: {
        Row: {
          id: string;
          name: string;
          artifact_type: string;
          request: string;
          expected_sections: unknown;
          required_facts: unknown;
          prohibited_expressions: unknown;
          expected_audience: string | null;
          expected_tone: string | null;
          required_output_format: string | null;
          references: unknown;
          template_id: string | null;
          business_profile_id: string | null;
          tags: unknown;
          enabled: boolean;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          name: string;
          artifact_type: string;
          request?: string;
          expected_sections?: unknown;
          required_facts?: unknown;
          prohibited_expressions?: unknown;
          expected_audience?: string | null;
          expected_tone?: string | null;
          required_output_format?: string | null;
          references?: unknown;
          template_id?: string | null;
          business_profile_id?: string | null;
          tags?: unknown;
          enabled?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          artifact_type?: string;
          request?: string;
          expected_sections?: unknown;
          required_facts?: unknown;
          prohibited_expressions?: unknown;
          expected_audience?: string | null;
          expected_tone?: string | null;
          required_output_format?: string | null;
          references?: unknown;
          template_id?: string | null;
          business_profile_id?: string | null;
          tags?: unknown;
          enabled?: boolean;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_benchmark_runs: {
        Row: {
          id: string;
          created_by: string;
          status: string;
          config: unknown;
          tags: unknown;
          memo: string | null;
          estimated_max_cost_usd: number | null;
          actual_cost_usd: number | null;
          case_count: number;
          pattern_count: number;
          result_count: number;
          idempotency_key: string;
          started_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          created_by: string;
          status?: string;
          config?: unknown;
          tags?: unknown;
          memo?: string | null;
          estimated_max_cost_usd?: number | null;
          actual_cost_usd?: number | null;
          case_count?: number;
          pattern_count?: number;
          result_count?: number;
          idempotency_key: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          created_by?: string;
          status?: string;
          config?: unknown;
          tags?: unknown;
          memo?: string | null;
          estimated_max_cost_usd?: number | null;
          actual_cost_usd?: number | null;
          case_count?: number;
          pattern_count?: number;
          result_count?: number;
          idempotency_key?: string;
          started_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_benchmark_results: {
        Row: {
          id: string;
          run_id: string | null;
          case_id: string | null;
          artifact_id: string | null;
          job_id: string | null;
          user_id: string | null;
          organization_id: string | null;
          artifact_type: string;
          artifact_sub_type: string | null;
          title: string | null;
          model: string | null;
          status: string;
          pattern_label: string | null;
          feature_flags: unknown;
          versions: unknown;
          quality: unknown;
          processing: unknown;
          context_info: unknown;
          cost_info: unknown;
          usage_info: unknown;
          rule_evaluation: unknown | null;
          owner_evaluation: unknown | null;
          user_evaluation: unknown | null;
          created_at: string;
          completed_at: string | null;
          updated_at: string;
        };
        Insert: {
          id: string;
          run_id?: string | null;
          case_id?: string | null;
          artifact_id?: string | null;
          job_id?: string | null;
          user_id?: string | null;
          organization_id?: string | null;
          artifact_type: string;
          artifact_sub_type?: string | null;
          title?: string | null;
          model?: string | null;
          status?: string;
          pattern_label?: string | null;
          feature_flags?: unknown;
          versions?: unknown;
          quality?: unknown;
          processing?: unknown;
          context_info?: unknown;
          cost_info?: unknown;
          usage_info?: unknown;
          rule_evaluation?: unknown | null;
          owner_evaluation?: unknown | null;
          user_evaluation?: unknown | null;
          created_at?: string;
          completed_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          run_id?: string | null;
          case_id?: string | null;
          artifact_id?: string | null;
          job_id?: string | null;
          user_id?: string | null;
          organization_id?: string | null;
          artifact_type?: string;
          artifact_sub_type?: string | null;
          title?: string | null;
          model?: string | null;
          status?: string;
          pattern_label?: string | null;
          feature_flags?: unknown;
          versions?: unknown;
          quality?: unknown;
          processing?: unknown;
          context_info?: unknown;
          cost_info?: unknown;
          usage_info?: unknown;
          rule_evaluation?: unknown | null;
          owner_evaluation?: unknown | null;
          user_evaluation?: unknown | null;
          created_at?: string;
          completed_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_artifact_feedback: {
        Row: {
          id: string;
          artifact_id: string;
          job_id: string | null;
          user_id: string;
          organization_id: string | null;
          rating_type: string;
          positive_reasons: unknown;
          negative_reasons: unknown;
          comment: string | null;
          artifact_type: string | null;
          artifact_sub_type: string | null;
          quality_score: number | null;
          model: string | null;
          prompt_version: string | null;
          specialist_version: string | null;
          template_id: string | null;
          template_version: string | null;
          knowledge_version: string | null;
          smart_context_version: string | null;
          quality_engine_version: string | null;
          regeneration_count: number | null;
          improvement_count: number | null;
          total_api_cost: number | null;
          input_tokens: number | null;
          output_tokens: number | null;
          final_used: boolean | null;
          downloaded: boolean | null;
          shared: boolean | null;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          artifact_id: string;
          job_id?: string | null;
          user_id: string;
          organization_id?: string | null;
          rating_type: string;
          positive_reasons?: unknown;
          negative_reasons?: unknown;
          comment?: string | null;
          artifact_type?: string | null;
          artifact_sub_type?: string | null;
          quality_score?: number | null;
          model?: string | null;
          prompt_version?: string | null;
          specialist_version?: string | null;
          template_id?: string | null;
          template_version?: string | null;
          knowledge_version?: string | null;
          smart_context_version?: string | null;
          quality_engine_version?: string | null;
          regeneration_count?: number | null;
          improvement_count?: number | null;
          total_api_cost?: number | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          final_used?: boolean | null;
          downloaded?: boolean | null;
          shared?: boolean | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          artifact_id?: string;
          job_id?: string | null;
          user_id?: string;
          organization_id?: string | null;
          rating_type?: string;
          positive_reasons?: unknown;
          negative_reasons?: unknown;
          comment?: string | null;
          artifact_type?: string | null;
          artifact_sub_type?: string | null;
          quality_score?: number | null;
          model?: string | null;
          prompt_version?: string | null;
          specialist_version?: string | null;
          template_id?: string | null;
          template_version?: string | null;
          knowledge_version?: string | null;
          smart_context_version?: string | null;
          quality_engine_version?: string | null;
          regeneration_count?: number | null;
          improvement_count?: number | null;
          total_api_cost?: number | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          final_used?: boolean | null;
          downloaded?: boolean | null;
          shared?: boolean | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_artifact_feedback_history: {
        Row: {
          id: string;
          feedback_id: string;
          artifact_id: string;
          user_id: string;
          rating_type: string;
          positive_reasons: unknown;
          negative_reasons: unknown;
          comment: string | null;
          changed_at: string;
        };
        Insert: {
          id: string;
          feedback_id: string;
          artifact_id: string;
          user_id: string;
          rating_type: string;
          positive_reasons?: unknown;
          negative_reasons?: unknown;
          comment?: string | null;
          changed_at?: string;
        };
        Update: {
          id?: string;
          feedback_id?: string;
          artifact_id?: string;
          user_id?: string;
          rating_type?: string;
          positive_reasons?: unknown;
          negative_reasons?: unknown;
          comment?: string | null;
          changed_at?: string;
        };
        Relationships: [];
      };
      atlas_artifact_quality_feedback: {
        Row: {
          id: string;
          artifact_id: string;
          result_id: string | null;
          user_id: string;
          role: string;
          rating_label: string | null;
          rating_score: number | null;
          reasons: unknown;
          free_text: string | null;
          dimensions: unknown;
          usability: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          artifact_id: string;
          result_id?: string | null;
          user_id: string;
          role?: string;
          rating_label?: string | null;
          rating_score?: number | null;
          reasons?: unknown;
          free_text?: string | null;
          dimensions?: unknown;
          usability?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          artifact_id?: string;
          result_id?: string | null;
          user_id?: string;
          role?: string;
          rating_label?: string | null;
          rating_score?: number | null;
          reasons?: unknown;
          free_text?: string | null;
          dimensions?: unknown;
          usability?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_quality_thresholds: {
        Row: {
          id: string;
          artifact_type: string;
          min_quality_score: number;
          warn_only: boolean;
          enabled: boolean;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          artifact_type: string;
          min_quality_score: number;
          warn_only?: boolean;
          enabled?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          artifact_type?: string;
          min_quality_score?: number;
          warn_only?: boolean;
          enabled?: boolean;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
