/**
 * Placeholder Supabase Database type.
 * Replace with generated types after running:
 *   npx supabase gen types typescript --project-id <id> > lib/supabase/database.types.ts
 */
export type Database = {
  public: {
    Tables: {
      projects: {
        Row: {
          id: string;
          user_id: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees: unknown;
          result: unknown | null;
          error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id?: string | null;
          title: string;
          work_request: string;
          status: string;
          progress: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          title?: string;
          work_request?: string;
          status?: string;
          progress?: number;
          assigned_employees?: unknown;
          result?: unknown | null;
          error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_user_state: {
        Row: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          domain: string;
          payload: unknown;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          domain?: string;
          payload?: unknown;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_billing_subscriptions: {
        Row: {
          user_id: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_price_id: string | null;
          plan_id: string;
          status: string;
          current_period_start: string | null;
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          updated_at: string;
          automations_suspended: boolean | null;
          payment_failure_grace_ends_at: string | null;
          plan_profile_synced_at: string | null;
        };
        Insert: {
          user_id: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id: string;
          status: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Update: {
          user_id?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_price_id?: string | null;
          plan_id?: string;
          status?: string;
          current_period_start?: string | null;
          current_period_end?: string | null;
          cancel_at_period_end?: boolean;
          updated_at?: string;
          automations_suspended?: boolean | null;
          payment_failure_grace_ends_at?: string | null;
          plan_profile_synced_at?: string | null;
        };
        Relationships: [];
      };
      atlas_stripe_webhook_events: {
        Row: {
          event_id: string;
          event_type: string | null;
          status: string;
          claimed_at: string;
          lease_expires_at: string;
          processed_at: string | null;
        };
        Insert: {
          event_id: string;
          event_type?: string | null;
          status?: string;
          claimed_at?: string;
          lease_expires_at?: string;
          processed_at?: string | null;
        };
        Update: {
          event_id?: string;
          event_type?: string | null;
          status?: string;
          claimed_at?: string;
          lease_expires_at?: string;
          processed_at?: string | null;
        };
        Relationships: [];
      };
      atlas_google_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          account_username: string | null;
          provider_user_id: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          account_username?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_dropbox_oauth_credentials: {
        Row: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope: string;
          connection_status: string;
          connected_at: string | null;
          last_used_at: string | null;
          account_email: string | null;
          account_name: string | null;
          account_picture_url: string | null;
          provider_user_id: string | null;
          error_message: string | null;
          encryption_key_version: number | null;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          access_token: string;
          refresh_token: string;
          expires_at: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          access_token?: string;
          refresh_token?: string;
          expires_at?: string;
          scope?: string;
          connection_status?: string;
          connected_at?: string | null;
          last_used_at?: string | null;
          account_email?: string | null;
          account_name?: string | null;
          account_picture_url?: string | null;
          provider_user_id?: string | null;
          error_message?: string | null;
          encryption_key_version?: number | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_settings: {
        Row: {
          user_id: string;
          enabled: boolean;
          mode: string;
          purpose: string;
          themes: unknown;
          audience: string;
          tone: string;
          frequency: string;
          days_of_week: unknown;
          post_times: unknown;
          timezone: string;
          include_hashtags: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          enabled?: boolean;
          mode?: string;
          purpose?: string;
          themes?: unknown;
          audience?: string;
          tone?: string;
          frequency?: string;
          days_of_week?: unknown;
          post_times?: unknown;
          timezone?: string;
          include_hashtags?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_x_autopost_runs: {
        Row: {
          id: string;
          user_id: string;
          slot_key: string;
          scheduled_for: string | null;
          status: string;
          mode: string;
          post_type: string | null;
          text: string | null;
          tweet_id: string | null;
          tweet_url: string | null;
          error_message: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          slot_key: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          slot_key?: string;
          scheduled_for?: string | null;
          status?: string;
          mode?: string;
          post_type?: string | null;
          text?: string | null;
          tweet_id?: string | null;
          tweet_url?: string | null;
          error_message?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_image_attachments: {
        Row: {
          id: string;
          user_id: string;
          job_id: string;
          original_file_name: string;
          mime_type: string;
          original_mime_type: string | null;
          original_bytes: number;
          processed_bytes: number;
          width: number;
          height: number;
          content_hash: string;
          original_storage_path: string;
          processed_storage_path: string;
          retention_policy: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          job_id?: string;
          original_file_name: string;
          mime_type: string;
          original_mime_type?: string | null;
          original_bytes: number;
          processed_bytes: number;
          width?: number;
          height?: number;
          content_hash: string;
          original_storage_path: string;
          processed_storage_path: string;
          retention_policy?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          job_id?: string;
          original_file_name?: string;
          mime_type?: string;
          original_mime_type?: string | null;
          original_bytes?: number;
          processed_bytes?: number;
          width?: number;
          height?: number;
          content_hash?: string;
          original_storage_path?: string;
          processed_storage_path?: string;
          retention_policy?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_push_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform: string | null;
          browser: string | null;
          device_name: string | null;
          user_agent: string | null;
          failure_count: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          last_used_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          endpoint: string;
          p256dh: string;
          auth_key: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          user_agent?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          endpoint?: string;
          p256dh?: string;
          auth_key?: string;
          platform?: string | null;
          browser?: string | null;
          device_name?: string | null;
          user_agent?: string | null;
          failure_count?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          last_used_at?: string | null;
        };
        Relationships: [];
      };
      atlas_deliverable_files: {
        Row: {
          id: string;
          user_id: string;
          file_name: string;
          format: string;
          mime_type: string;
          is_placeholder: boolean;
          source_content: string;
          base_file_name: string;
          size_bytes: number | null;
          content_base64: string | null;
          generated_at: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          file_name: string;
          format: string;
          mime_type: string;
          is_placeholder?: boolean;
          source_content: string;
          base_file_name: string;
          size_bytes?: number | null;
          content_base64?: string | null;
          generated_at: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          file_name?: string;
          format?: string;
          mime_type?: string;
          is_placeholder?: boolean;
          source_content?: string;
          base_file_name?: string;
          size_bytes?: number | null;
          content_base64?: string | null;
          generated_at?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_reliability_events: {
        Row: {
          id: string;
          metric_key: string | null;
          outcome: string | null;
          duration_ms: number | null;
          job_id: string | null;
          diagnostic_id: string | null;
          user_id: string | null;
          stage: string | null;
          severity: string | null;
          error_code: string | null;
          message: string | null;
          error_message: string | null;
          metadata: unknown;
          created_at: string;
        };
        Insert: {
          id?: string;
          metric_key?: string | null;
          outcome?: string | null;
          duration_ms?: number | null;
          job_id?: string | null;
          diagnostic_id?: string | null;
          user_id?: string | null;
          stage?: string | null;
          severity?: string | null;
          error_code?: string | null;
          message?: string | null;
          error_message?: string | null;
          metadata?: unknown;
          created_at?: string;
        };
        Update: {
          id?: string;
          metric_key?: string | null;
          outcome?: string | null;
          duration_ms?: number | null;
          job_id?: string | null;
          diagnostic_id?: string | null;
          user_id?: string | null;
          stage?: string | null;
          severity?: string | null;
          error_code?: string | null;
          message?: string | null;
          error_message?: string | null;
          metadata?: unknown;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_user_notifications: {
        Row: {
          notification_id: string;
          owner_id: string;
          organization_id: string | null;
          audience: string;
          source_type: string | null;
          source_id: string | null;
          event_type: string;
          channel: string;
          title: string;
          body: string;
          severity: string | null;
          status: string;
          read_at: string | null;
          delivered_at: string | null;
          failed_at: string | null;
          retry_count: number;
          next_retry_at: string | null;
          max_retries: number;
          idempotency_key: string;
          diagnostic_id: string | null;
          metadata: unknown;
          related_task_id: string | null;
          related_service: string | null;
          action_url: string | null;
          target_type: string | null;
          target_id: string | null;
          workflow_run_id: string | null;
          deliverable_id: string | null;
          request_id: string | null;
          automation_id: string | null;
          line_event: string | null;
          event_category: string | null;
          push_sent_at: string | null;
          push_failed_at: string | null;
          push_failure_reason: string | null;
          created_at: string;
          updated_at: string;
          expires_at: string | null;
          deleted_at: string | null;
        };
        Insert: {
          notification_id: string;
          owner_id: string;
          organization_id?: string | null;
          audience?: string;
          source_type?: string | null;
          source_id?: string | null;
          event_type: string;
          channel?: string;
          title: string;
          body: string;
          severity?: string | null;
          status?: string;
          read_at?: string | null;
          delivered_at?: string | null;
          failed_at?: string | null;
          retry_count?: number;
          next_retry_at?: string | null;
          max_retries?: number;
          idempotency_key: string;
          diagnostic_id?: string | null;
          metadata?: unknown;
          related_task_id?: string | null;
          related_service?: string | null;
          action_url?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          workflow_run_id?: string | null;
          deliverable_id?: string | null;
          request_id?: string | null;
          automation_id?: string | null;
          line_event?: string | null;
          event_category?: string | null;
          push_sent_at?: string | null;
          push_failed_at?: string | null;
          push_failure_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          notification_id?: string;
          owner_id?: string;
          organization_id?: string | null;
          audience?: string;
          source_type?: string | null;
          source_id?: string | null;
          event_type?: string;
          channel?: string;
          title?: string;
          body?: string;
          severity?: string | null;
          status?: string;
          read_at?: string | null;
          delivered_at?: string | null;
          failed_at?: string | null;
          retry_count?: number;
          next_retry_at?: string | null;
          max_retries?: number;
          idempotency_key?: string;
          diagnostic_id?: string | null;
          metadata?: unknown;
          related_task_id?: string | null;
          related_service?: string | null;
          action_url?: string | null;
          target_type?: string | null;
          target_id?: string | null;
          workflow_run_id?: string | null;
          deliverable_id?: string | null;
          request_id?: string | null;
          automation_id?: string | null;
          line_event?: string | null;
          event_category?: string | null;
          push_sent_at?: string | null;
          push_failed_at?: string | null;
          push_failure_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          expires_at?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      atlas_notification_dlq: {
        Row: {
          id: string;
          notification_id: string;
          user_id: string;
          channel: string;
          title: string;
          message: string;
          attempt_count: number;
          last_error: string | null;
          payload: unknown;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          notification_id: string;
          user_id: string;
          channel: string;
          title: string;
          message: string;
          attempt_count?: number;
          last_error?: string | null;
          payload?: unknown;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          notification_id?: string;
          user_id?: string;
          channel?: string;
          title?: string;
          message?: string;
          attempt_count?: number;
          last_error?: string | null;
          payload?: unknown;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_side_effect_claims: {
        Row: {
          id: string;
          user_id: string;
          idempotency_key: string;
          provider: string;
          action_type: string;
          automation_id: string | null;
          run_id: string | null;
          occurrence_key: string | null;
          destination_fingerprint: string;
          status: string;
          lease_owner: string | null;
          lease_expires_at: string | null;
          attempt_count: number;
          max_attempts: number;
          provider_resource_id: string | null;
          provider_request_id: string | null;
          evidence: unknown;
          result_payload: unknown;
          last_error_code: string | null;
          last_error_message: string | null;
          created_at: string;
          updated_at: string;
          completed_at: string | null;
        };
        Insert: {
          id: string;
          user_id: string;
          idempotency_key: string;
          provider: string;
          action_type: string;
          automation_id?: string | null;
          run_id?: string | null;
          occurrence_key?: string | null;
          destination_fingerprint?: string;
          status?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          provider_resource_id?: string | null;
          provider_request_id?: string | null;
          evidence?: unknown;
          result_payload?: unknown;
          last_error_code?: string | null;
          last_error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          idempotency_key?: string;
          provider?: string;
          action_type?: string;
          automation_id?: string | null;
          run_id?: string | null;
          occurrence_key?: string | null;
          destination_fingerprint?: string;
          status?: string;
          lease_owner?: string | null;
          lease_expires_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          provider_resource_id?: string | null;
          provider_request_id?: string | null;
          evidence?: unknown;
          result_payload?: unknown;
          last_error_code?: string | null;
          last_error_message?: string | null;
          created_at?: string;
          updated_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      atlas_rate_limit_counters: {
        Row: {
          id: string;
          bucket: string;
          subject_key: string;
          window_started_at: string;
          window_ms: number;
          hit_count: number;
          last_hit_at: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          bucket: string;
          subject_key: string;
          window_started_at: string;
          window_ms: number;
          hit_count?: number;
          last_hit_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          bucket?: string;
          subject_key?: string;
          window_started_at?: string;
          window_ms?: number;
          hit_count?: number;
          last_hit_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_household_ledger_entries: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          currency: string;
          occurred_at: string;
          occurred_on: string;
          category: string;
          merchant: string;
          item_name: string;
          description: string;
          source: string;
          receipt_id: string | null;
          source_image_ids: unknown;
          quantity: number | null;
          unit_price: number | null;
          tax: number | null;
          payment_method: string | null;
          money_use: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          amount?: number;
          currency?: string;
          occurred_at: string;
          occurred_on: string;
          category?: string;
          merchant?: string;
          item_name?: string;
          description?: string;
          source?: string;
          receipt_id?: string | null;
          source_image_ids?: unknown;
          quantity?: number | null;
          unit_price?: number | null;
          tax?: number | null;
          payment_method?: string | null;
          money_use?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount?: number;
          currency?: string;
          occurred_at?: string;
          occurred_on?: string;
          category?: string;
          merchant?: string;
          item_name?: string;
          description?: string;
          source?: string;
          receipt_id?: string | null;
          source_image_ids?: unknown;
          quantity?: number | null;
          unit_price?: number | null;
          tax?: number | null;
          payment_method?: string | null;
          money_use?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automations: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string;
          status: string;
          trigger: unknown;
          workflow: unknown;
          execution_policy: unknown;
          notification_policy: unknown;
          instruction: unknown;
          memory_policy: unknown;
          legacy_automation_id: string | null;
          schema_version: number;
          last_run_at: string | null;
          next_run_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          name: string;
          description?: string;
          status: string;
          trigger: unknown;
          workflow: unknown;
          execution_policy: unknown;
          notification_policy: unknown;
          instruction: unknown;
          memory_policy: unknown;
          legacy_automation_id?: string | null;
          schema_version?: number;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string;
          status?: string;
          trigger?: unknown;
          workflow?: unknown;
          execution_policy?: unknown;
          notification_policy?: unknown;
          instruction?: unknown;
          memory_policy?: unknown;
          legacy_automation_id?: string | null;
          schema_version?: number;
          last_run_at?: string | null;
          next_run_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automation_runs: {
        Row: {
          id: string;
          automation_id: string;
          user_id: string;
          status: string;
          run_key: string;
          idempotency_key: string;
          schedule_occurrence_key: string | null;
          trigger_type: string;
          scheduled_for: string | null;
          queued_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          attempt_count: number;
          max_attempts: number;
          last_error_code: string | null;
          last_error_message: string | null;
          resolved_instruction: unknown | null;
          memory_references: unknown;
          status_history: unknown;
          approval_expires_at: string | null;
          result_summary: string | null;
          next_retry_at: string | null;
          payload: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          automation_id: string;
          user_id: string;
          status: string;
          run_key: string;
          idempotency_key: string;
          schedule_occurrence_key?: string | null;
          trigger_type: string;
          scheduled_for?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          resolved_instruction?: unknown | null;
          memory_references?: unknown;
          status_history?: unknown;
          approval_expires_at?: string | null;
          result_summary?: string | null;
          next_retry_at?: string | null;
          payload?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          automation_id?: string;
          user_id?: string;
          status?: string;
          run_key?: string;
          idempotency_key?: string;
          schedule_occurrence_key?: string | null;
          trigger_type?: string;
          scheduled_for?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          attempt_count?: number;
          max_attempts?: number;
          last_error_code?: string | null;
          last_error_message?: string | null;
          resolved_instruction?: unknown | null;
          memory_references?: unknown;
          status_history?: unknown;
          approval_expires_at?: string | null;
          result_summary?: string | null;
          next_retry_at?: string | null;
          payload?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_automation_jobs: {
        Row: {
          id: string;
          user_id: string;
          automation_id: string | null;
          job_type: string;
          status: string;
          scheduled_at: string | null;
          queued_at: string | null;
          started_at: string | null;
          completed_at: string | null;
          failed_at: string | null;
          current_step: string | null;
          progress_percent: number;
          attempt_count: number;
          max_attempts: number;
          next_retry_at: string | null;
          last_error_code: string | null;
          last_error_message: string | null;
          result_summary: string | null;
          artifact_id: string | null;
          external_result_id: string | null;
          external_result_url: string | null;
          idempotency_key: string;
          push_status: string;
          auto_recovered: boolean;
          steps: unknown;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          user_id: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          automation_id?: string | null;
          job_type?: string;
          status?: string;
          scheduled_at?: string | null;
          queued_at?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          failed_at?: string | null;
          current_step?: string | null;
          progress_percent?: number;
          attempt_count?: number;
          max_attempts?: number;
          next_retry_at?: string | null;
          last_error_code?: string | null;
          last_error_message?: string | null;
          result_summary?: string | null;
          artifact_id?: string | null;
          external_result_id?: string | null;
          external_result_url?: string | null;
          idempotency_key?: string;
          push_status?: string;
          auto_recovered?: boolean;
          steps?: unknown;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_monitor_check_runs: {
        Row: {
          id: string;
          check_id: string;
          status: string;
          severity: string;
          observed_at: string;
          metrics: unknown;
          instance_id: string | null;
          synthetic: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          check_id: string;
          status: string;
          severity?: string;
          observed_at?: string;
          metrics?: unknown;
          instance_id?: string | null;
          synthetic?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          check_id?: string;
          status?: string;
          severity?: string;
          observed_at?: string;
          metrics?: unknown;
          instance_id?: string | null;
          synthetic?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_alert_incidents: {
        Row: {
          id: string;
          fingerprint: string;
          check_id: string;
          severity: string;
          status: string;
          title: string;
          summary: string;
          details: unknown;
          failure_class: string;
          affected_users_estimate: number;
          first_seen_at: string;
          last_seen_at: string;
          resolved_at: string | null;
          last_notified_at: string | null;
          notify_count: number;
          continuation_count: number;
          claim_owner: string | null;
          claim_until: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          fingerprint: string;
          check_id: string;
          severity: string;
          status?: string;
          title: string;
          summary: string;
          details?: unknown;
          failure_class?: string;
          affected_users_estimate?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          resolved_at?: string | null;
          last_notified_at?: string | null;
          notify_count?: number;
          continuation_count?: number;
          claim_owner?: string | null;
          claim_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          fingerprint?: string;
          check_id?: string;
          severity?: string;
          status?: string;
          title?: string;
          summary?: string;
          details?: unknown;
          failure_class?: string;
          affected_users_estimate?: number;
          first_seen_at?: string;
          last_seen_at?: string;
          resolved_at?: string | null;
          last_notified_at?: string | null;
          notify_count?: number;
          continuation_count?: number;
          claim_owner?: string | null;
          claim_until?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atlas_alert_deliveries: {
        Row: {
          id: string;
          incident_id: string;
          delivery_kind: string;
          channel: string;
          status: string;
          dedupe_key: string;
          claimed_by: string;
          claimed_at: string;
          delivered_at: string | null;
          error_code: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          incident_id: string;
          delivery_kind: string;
          channel: string;
          status?: string;
          dedupe_key: string;
          claimed_by: string;
          claimed_at?: string;
          delivered_at?: string | null;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          incident_id?: string;
          delivery_kind?: string;
          channel?: string;
          status?: string;
          dedupe_key?: string;
          claimed_by?: string;
          claimed_at?: string;
          delivered_at?: string | null;
          error_code?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      atlas_monitor_injections: {
        Row: {
          id: string;
          injection_kind: string;
          active: boolean;
          expires_at: string;
          created_by: string | null;
          metadata: unknown;
          cleared_at: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          injection_kind: string;
          active?: boolean;
          expires_at: string;
          created_by?: string | null;
          metadata?: unknown;
          cleared_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          injection_kind?: string;
          active?: boolean;
          expires_at?: string;
          created_by?: string | null;
          metadata?: unknown;
          cleared_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      atlas_consume_rate_limit: {
        Args: {
          p_bucket: string;
          p_subject_key: string;
          p_max: number;
          p_window_ms: number;
          p_min_interval_ms?: number;
        };
        // PostgREST may return jsonb object or TABLE rows as an array of 1.
        Returns: unknown;
      };
      atlas_claim_side_effect: {
        Args: {
          p_id: string;
          p_user_id: string;
          p_lease_owner: string;
          p_lease_ms?: number;
        };
        Returns: Database["public"]["Tables"]["atlas_side_effect_claims"]["Row"] | null;
      };
      atlas_claim_work_queue_jobs: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      atlas_claim_x_post_jobs: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
      atlas_claim_alert_delivery: {
        Args: {
          p_id: string;
          p_incident_id: string;
          p_delivery_kind: string;
          p_channel: string;
          p_dedupe_key: string;
          p_claimed_by: string;
        };
        Returns: Database["public"]["Tables"]["atlas_alert_deliveries"]["Row"] | null;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
